### ISSUE TITLE
Jina Hello World is missing dependencies when run from docker

### ISSUE THREAD

**Issue by grofte** [jina-ai/jina#1078]
**Describe your problem**
I ran the docker Hello World as described in the documentation and it is lacking the PIL module (at the very least).

Error message:

```
        gateway@ 1[E]:callback() may not work properly due to the bad response: encode-1(MyEncoder) throws ModuleNotFoundError("No module named 'PIL'")
        gateway@ 1[E]:[pod: "encode-1"
pod_id: "ff6192ccab"
executor: "MyEncoder"
exception: "ModuleNotFoundError(\"No module named \'PIL\'\")"
traceback: "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 291, in msg_callback\n    self.zmqlet.send_message(self._callback(msg))\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 265, in _callback\n    self.pre_hook(msg).handle(msg).post_hook(msg)\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 159, in handle\n    self.executor(self.request_type)\n  File \"/usr/local/lib/python3.7/site-packages/jina/executors/__init__.py\", line 568, in __call__\n    d()\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 243, in __call__\n    self._traverse_apply(self.req.docs, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 248, in _traverse_apply\n    self._traverse_rec(docs, None, None, [], *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 261, in _traverse_rec\n    self._apply_all(docs, parent_doc, parent_edge_type, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/convert.py\", line 41, in _apply_all\n    self.convert(doc)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/convert.py\", line 183, in convert\n    d.uri = self.png_convertor(arr)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/convert.py\", line 152, in png_convertor\n    from PIL import Image\nModuleNotFoundError: No module named \'PIL\'\n"
time {
  seconds: 1602598087
  nanos: 547696000
}
]
```

**What is your guess?**
I am guessing that you are not building the image with all dependencies? Then maybe you should distribute a dockerfile for running Hello World instead?

---

**Environment**
jina                          0.6.6
jina-proto                    0.0.62
jina-vcs-tag                  9247874
libzmq                        4.3.1
pyzmq                         1.16.2
protobuf                      3.6.1
proto-backend                 cpp
grpcio                        1.16.1
ruamel.yaml                   0.16.12
python                        3.7.6
platform                      Linux
platform-release              5.4.0-48-generic
platform-version              #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
architecture                  x86_64
processor                     
jina-resources                /usr/local/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              9247874
JINA_WARN_UNNAMED             (unset)

**Comment by JoanFM** [comment]
Hello @grofte,

Thanks for trying out Jina, do you have the detailed steps that you took to run the `hello-world`? was it `jina hello-world` or `docker run -v ...`?

Thank you very much

**Comment by grofte** [comment]
Yes, sorry. I used the Linux option

`docker run -v "$(pwd)/j:/j" jinaai/jina hello-world --workdir /j && xdg-open j/hello-world.html`

from https://docs.jina.ai/chapters/helloworld/index.html

**Comment by JoanFM** [comment]
Hey @grofte ,

thanks for the great catch!

PR #1079 has been created to fix the issue, it should be fixed soon

**Comment by JoanFM** [comment]
Hello @grofte ,

The issue should already be fixed.

Would you give it a try?

Thank you very much for your help and for raising the issue.

**Comment by grofte** [comment]
So I deleted the old image and ran the command again. This time there are images on the left ('query') when it opens the html page but top-k results is still empty. 

If I scroll up I get this error message:

```
          index@31[E]:'NoneType' object has no attribute 'header'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py", line 291, in msg_callback
    self.zmqlet.send_message(self._callback(msg))
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py", line 265, in _callback
    self.pre_hook(msg).handle(msg).post_hook(msg)
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py", line 159, in handle
    self.executor(self.request_type)
  File "/usr/local/lib/python3.7/site-packages/jina/executors/__init__.py", line 568, in __call__
    d()
  File "/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py", line 243, in __call__
    self._traverse_apply(self.req.docs, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py", line 248, in _traverse_apply
    self._traverse_rec(docs, None, None, [], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py", line 261, in _traverse_rec
    self._apply_all(docs, parent_doc, parent_edge_type, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/drivers/index.py", line 44, in _apply_all
    self.exec_fn(keys, values)
  File "/usr/local/lib/python3.7/site-packages/jina/executors/decorators.py", line 26, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/executors/indexers/keyvalue.py", line 60, in add
    self.write_handler.header.write(
AttributeError: 'NoneType' object has no attribute 'header'
          index@22[I]:received "control" from gateway▸encode-head▸encode-1▸encode-tail▸index-head▸index-2▸⚐
          index@25[I]:received "index" from gateway▸encode-head▸encode-1▸encode-tail▸index-head▸index-2▸⚐
        gateway@ 1[E]:callback() may not work properly due to the bad response: index-2(CompoundIndexer) throws AttributeError("'NoneType' object has no attribute 'header'")
        gateway@ 1[E]:[pod: "index-2"
pod_id: "165cad01de"
executor: "CompoundIndexer"
exception: "AttributeError(\"\'NoneType\' object has no attribute \'header\'\")"
traceback: "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 291, in msg_callback\n    self.zmqlet.send_message(self._callback(msg))\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 265, in _callback\n    self.pre_hook(msg).handle(msg).post_hook(msg)\n  File \"/usr/local/lib/python3.7/site-packages/jina/peapods/pea.py\", line 159, in handle\n    self.executor(self.request_type)\n  File \"/usr/local/lib/python3.7/site-packages/jina/executors/__init__.py\", line 568, in __call__\n    d()\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 243, in __call__\n    self._traverse_apply(self.req.docs, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 248, in _traverse_apply\n    self._traverse_rec(docs, None, None, [], *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/__init__.py\", line 261, in _traverse_rec\n    self._apply_all(docs, parent_doc, parent_edge_type, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/drivers/index.py\", line 44, in _apply_all\n    self.exec_fn(keys, values)\n  File \"/usr/local/lib/python3.7/site-packages/jina/executors/decorators.py\", line 26, in arg_wrapper\n    f = func(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jina/executors/indexers/keyvalue.py\", line 60, in add\n    self.write_handler.header.write(\nAttributeError: \'NoneType\' object has no attribute \'header\'\n"
time {
  seconds: 1602681624
  nanos: 897978000
}
]
```

**Comment by JoanFM** [comment]
Hello @grofte,

Could you run it again making sure that the `folder` created by the previous run is removed? I think there has been some conflict there.

Thank you very much

**Comment by grofte** [comment]
Ah cool, works now. Even replies to whatever this is 

![image](https://user-images.githubusercontent.com/7976840/96249762-f4750280-0fad-11eb-9c51-21ed1422bb7b.png)
