### ISSUE TITLE
crash when sharding without batching 

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#1229]
**Describe the bug**

When attempting to upgrade the multires lyrics examples to use sharding, I encountered a bug that produced the following error at query time:

```
Traceback (most recent call last):
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/peapods/pea.py", line 292, in msg_callback
    self.zmqlet.send_message(self._callback(msg))
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/peapods/pea.py", line 266, in _callback
    self.pre_hook(msg).handle(msg).post_hook(msg)
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/peapods/pea.py", line 160, in handle
    self.executor(self.request_type)
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/executors/__init__.py", line 570, in __call__
    d()
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/drivers/__init__.py", line 251, in __call__
    self._traverse_apply(self.req.docs, *args, **kwargs)
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/drivers/__init__.py", line 268, in _traverse_apply
    **kwargs,
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/drivers/__init__.py", line 281, in _traverse_rec
    doc.chunks, doc, 'chunks', path[1:], *args, **kwargs
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/drivers/__init__.py", line 284, in _traverse_rec
    self._apply_all(docs, parent_doc, parent_edge_type, *args, **kwargs)
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/drivers/search.py", line 124, in _apply_all
    idx, dist = self.exec_fn(embed_vecs, top_k=int(self.top_k))
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/executors/indexers/vector.py", line 279, in query
    dist = self._euclidean(_keys, self.query_handler)
  File "/home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/executors/decorators.py", line 241, in arg_wrapper
    for b in batch_iterator(data[:total_size], b_size, split_over_axis, yield_slice=yield_slice):
TypeError: 'NoneType' object is not subscriptable
```

See discussion and experiments in [this PR](https://github.com/jina-ai/examples/pull/271)

The problem seems to be as follows.

1. We should inform users that if they use sharding, they need to use batching.
2. If a shard is empty, is should still return an empty list of results. 

**Describe how you solve it**

In order to fix this, we **need** to use batching. See ex. v3 in the PR above.

---

**Environment**

```
$ jina -vf
jina                          0.7.4
jina-proto                    0.0.74
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.4
protobuf                      3.13.0
proto-backend                 cpp
grpcio                        1.33.2
ruamel.yaml                   0.16.12
python                        3.7.5
platform                      Linux
platform-release              5.4.0-52-generic
platform-version              #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/cristian/envs/lyrics/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)
```

**Screenshots**

Workspace directory, when **not** using batch (ex v1 and v2)

![image](https://user-images.githubusercontent.com/8330330/98345387-e5b1c680-2014-11eb-9c0d-c14171e672f3.png)

Workspace directory, when we use batching (ex v3)

![image](https://user-images.githubusercontent.com/8330330/98345425-f2361f00-2014-11eb-8805-62d2538d686b.png)

**Comment by JoanFM** [comment]
Here the issue is that when `batch_size` is larger than the `size` of the data, the load balancer in `HeadPea` does not send any data to that shard, leaving this `shard` empty. (That is for me not an issue).

The thing is we need to decide what to do when a `shard` is empty (I think the `indexer` should be robust to not having any data and maybe just raise a `warning` that the index in that `shard` is empty.

**Note**
When I talk about shard is to understand each other, but ideally a `Pea` , `driver` or `executor` should be unaware of them being a `shard` (at least for now). 

**Wrap up**
Need to make `Indexers` and `SearchDrivers` (robust to having no documents) indexed and just return no matches. (Most of the effort should be make on testing and integration testing).
