### ISSUE TITLE
Jina cannot save custom Indexer

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1678]
Hey Jina team,
today we build a custom indexer. However, Jina raises the following error when saving the Indexer at index-time:

```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 88, in run
     self.runtime.teardown()
   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 44, in teardown
     self._executor.close()
   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/__init__.py", line 155, in close
     super().close()
   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 399, in close
     self.save()
   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 345, in save
     pickle.dump(self, fp)
 _pickle.PicklingError: Can't pickle <class 'jinahub.CustomDocIndexer'>: import of module 'jinahub' failed
```
### Simplified example:
**File structure:**
```
/index-flow.yml
/pods
  /doc_executor.py
  /doc.yml
  # ... other pods
```

**index-flow.yml:**
```
!AsyncFlow
pods:
  crafter:
    uses: pods/craft.yml
  encoder:
    uses: pods/encode.yml
  chunk_idx:
    uses: pods/chunk.yml
  doc_idx:
    uses: pods/doc.yml  # FAILS HERE
```

**doc.yml:**
```
!CustomDocIndexer
with:
  index_filename: doc.gz
metas:
  name: doc_idx  # a customized name
  workspace: $PATH_WORKSPACE
  py_modules: doc_executor.py
```

**doc_executor.py:**
```
from jina.executors.indexers.keyvalue import BinaryPbIndexer

class CustomDocIndexer(BinaryPbIndexer):
    pass
```

**Comment by janandreschweiger** [comment]
We figured out a different setup, that has no need to persist a custom indexer.

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

that may be interesting to take a look at, can u try setting the class attribute `force_register = True`?
