### ISSUE TITLE
Issue in basic fetch result notebook. 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/jina#1737]
The following errors occurs for me. Reproduced both locally and on binder

`BadClient: something wrong when running the eventloop, result can not be retrieved`

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/helper.py", line 52, in arg_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not Response

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/jina/helper.py", line 670, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/base.py", line 132, in _get_results
    callback_exec(response=resp,
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/helper.py", line 69, in callback_exec
    _safe_callback(on_always, continue_on_error, logger)(response)
  File "/usr/local/lib/python3.8/dist-packages/jina/clients/helper.py", line 58, in arg_wrapper
    raise BadClientCallback(err_msg) from ex
jina.excepts.BadClientCallback: uncaught exception in callback write(): TypeError('write() argument must be str, not Response')`

**Comment by nan-wang** [comment]
fixed in #1748
