### ISSUE TITLE
Failed to build hub component locally

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#1935]
**Describe the bug**
Building the mongo indexer locally:
```
jina hub build --pull --prune-images --raise-error --host-info --test-uses --timeout-ready 30000 ./MongoDBIndexer/Dockerfile
```
can lead to the following error:
```
Traceback (most recent call last):
  File "/Users/florianhonicke/experiments/jina/jina-env/bin/jina", line 33, in <module>
    sys.exit(load_entry_point('jina', 'console_scripts', 'jina')())
  File "/Users/florianhonicke/jina/jina/cli/__init__.py", line 90, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/Users/florianhonicke/jina/jina/cli/api.py", line 109, in hub
    getattr(HubIO(args), args.hub)()
  File "/Users/florianhonicke/jina/jina/jina/docker/hubio.py", line 462, in build
    raise HubBuilderError(_excepts)
jina.excepts.HubBuilderError: [HubBuilderBuildError(KeyError('pop from an empty set'))]
```
The reason might be that there is a `build_history` without `logs`

**Comment by florian-hoenicke** [comment]
The issue was that I specified the full path to the Dockerfile. When I just point to the folder, it works.
