### ISSUE TITLE
Searching with FaissIndexer fails for empty workspace

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#2554]
Hey everyone,

we recently switched to the FaissIndexer. We discovered that any search fails with the FaissIndexer if the workspace is empty. So this happens if nothing was indexed in the first place or all documents were deleted. Jina v1.0.8 and v1.3.0 fails with the following error stack:

```
dev_ai            |     AsyncClient@ 1[S]:connected to the gateway at 0.0.0.0:49549!
search |█                   | 📃      0 ⏱️ 0.0s 🐎 0.0/s      0   requestssearch ...             gateway@37[I]:prefetching 50 requests...
dev_ai            |         gateway@37[W]:if this takes too long, you may want to take smaller "--prefetch" or ask client to reduce "--request-size"
dev_ai            |         encoder@25[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸⚐
dev_ai            | DEBUG | Message: Encoding 1 paragraphs
dev_ai            | 
Batches:   0%|          | 0/1 [00:00<?, ?it/s]        gateway@37[I]:prefetching 50 requests takes 0 seconds (0.01s)
Batches: 100%|██████████| 1/1 [00:00<00:00,  2.27it/s]        encoder@25[I]:#sent: 1 #recv: 2 sent_size: 3.6 KB recv_size: 924 Bytes
dev_ai            |       chunk_idx@28[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸⚐
dev_ai            |    FaissIndexer@28[W]:you can not query from FaissIndexer as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are querying data then the index file must be empty or broken.
dev_ai            |       chunk_idx@28[I]:#sent: 1 #recv: 2 sent_size: 5.1 KB recv_size: 7.1 KB
dev_ai            |       chunk_idx@28[E]:AttributeError("'NoneType' object has no attribute 'search'")
dev_ai            |  add "--quiet-error" to suppress the exception details
dev_ai            | Traceback (most recent call last):
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 203, in _msg_callback
dev_ai            |     self._zmqlet.send_message(self._callback(msg))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 189, in _callback
dev_ai            |     self._pre_hook(msg)._handle(msg)._post_hook(msg)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 182, in _handle
dev_ai            |     self._executor(self.request_type)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 587, in __call__
dev_ai            |     d()
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/__init__.py", line 392, in __call__
dev_ai            |     self._apply_all(documents, *args, **kwargs)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/search.py", line 177, in _apply_all
dev_ai            |     idx, dist = self.exec_fn(embed_vecs, top_k=int(self.top_k))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/hub/indexers/vector/FaissIndexer/__init__.py", line 133, in query
dev_ai            |     dist, ids = self.query_handler.search(vecs, top_k)
dev_ai            | AttributeError: 'NoneType' object has no attribute 'search'
dev_ai            |          ranker@31[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸ranker/ZEDRuntime▸⚐
dev_ai            |          ranker@31[I]:#sent: 1 #recv: 2 sent_size: 5.1 KB recv_size: 10.0 KB
dev_ai            |         doc_idx@34[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸ranker/ZEDRuntime▸doc_idx/ZEDRuntime▸⚐
dev_ai            |         doc_idx@34[I]:#sent: 1 #recv: 2 sent_size: 5.2 KB recv_size: 10.1 KB
search |█                   | 📃    100 ⏱️ 0.5s 🐎 220.8/s      1   requestsINFO:     10.0.0.17:53068 - "POST /search/?query=microsoft HTTP/1.1" 200 OK
dev_ai            | search takes 0 seconds (0.45s)
```

We appreciate any help. Just let me know if you need any more details. Thank you!

**Comment by JoanFM** [comment]
Hey @janandreschweiger,

I do not understand, what is the expected behavior here? Are u suggesting to fail silently and just return empty matches?

Thanks,

Joan

**Comment by janandreschweiger** [comment]
Hey @JoanFM, yes we expect to just return no matches like the NumpyIndexer.

**Comment by JoanFM** [comment]
Hey @janandreschweiger, right now we wont have a hub submodule and no patch release to fix the issue but we can consider in the next port to 2.0.

In the meantime, maybe u can build your own changes in the hub?

**Comment by janandreschweiger** [comment]
That's what we expected @JoanFM. We already have a custom logic in place that checks if no documents were indexed. But, as documents can be deleted as well, we'd like to see a fix in Jina v2.0.

**Comment by FionnD** [comment]
Thanks for reporting it @janandreschweiger , let's keep this open issue @JoanFM so we can implement this post 2.0 once Hubble is done?

**Comment by JoanFM** [comment]
@cristianmtr can u make sure this is taken care in the new version?

**Comment by cristianmtr** [comment]
@JoanFM  https://github.com/jina-ai/executor-indexers/pull/22
