### ISSUE TITLE
Jina : Windows Not Supported 

### ISSUE THREAD

**Issue by JOS-RE** [jina-ai/jina#2811]
**Describe the feature**
Jina is not supported in Windows single lang 10

**Your proposal**
It must be compatible in Windows 10 latest version. (normal)

- - -

```
ERROR: Command errored out with exit status 1:
     command: 'c:\users\joshith reddy\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Joshith Reddy\\AppData\\Local\\Temp\\pip-install-l70otob9\\uvloop_7b65578d14364a3ea19c38d12c62ca00\\setup.py'"'"'; __file__='"'"'C:\\Users\\Joshith Reddy\\AppData\\Local\\Temp\\pip-install-l70otob9\\uvloop_7b65578d14364a3ea19c38d12c62ca00\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Joshith Reddy\AppData\Local\Temp\pip-pip-egg-info-4k7d668c'
         cwd: C:\Users\Joshith Reddy\AppData\Local\Temp\pip-install-l70otob9\uvloop_7b65578d14364a3ea19c38d12c62ca00\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Joshith Reddy\AppData\Local\Temp\pip-install-l70otob9\uvloop_7b65578d14364a3ea19c38d12c62ca00\setup.py", line 8, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
```

**Environment**

**Screenshots**
![image](https://user-images.githubusercontent.com/77195199/123872999-739b4280-d953-11eb-9045-ea9a7434e5e1.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200539606790616) by [Unito](https://www.unito.io)

**Comment by JoanFM** [comment]
Hey @JOS-RE , 

Windows is not currently supported. You can install WSL for it.

Another thing that may be worth trying is to set the environment variable JINA_DISABLE_UVLOOP to True, and see if it may work

**Comment by JOS-RE** [comment]
Could you provide a video that demonstrates the entire Installation process.

**Comment by Bhavya1912** [comment]
install WSL for it.
