### ISSUE TITLE
AttributeError: '_RunThread' object has no attribute 'result'

### ISSUE THREAD

**Issue by vwoloszyn** [jina-ai/jina#2846]
I'm trying to reproduce the examples on the README.MD. Although searching using http://0.0.0.0:5000/docs looks good, I get an exception when I try to use the Client. 

Code:

from jina import Client, Document
from jina.types.request import Response

def print_matches(resp: Response):  # the callback function invoked when task is done
    for idx, d in enumerate(resp.docs[0].matches[:3]):  # print top-3 matches
        print(f'[{idx}]{d.scores["euclid"].value:2f}: "{d.text}"')

c = Client(protocol='http', port_expose=5000 )  # connect to localhost:12345
c.post('/search', Document(text='@request(on=something)'), on_done=print_matches)

error:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/jina/helper.py", line 1071, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/jina/clients/mixin.py", line 49, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/usr/local/lib/python3.9/site-packages/jina/clients/base/http.py", line 83, in _get_results
    r_status, r_str = await resp
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.9/site-packages/jina/clients/base/http.py", line 21, in _get_http_response
    resp_str = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://0.0.0.0:5000/post')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/jina/helper.py in run_async(func, *args, **kwargs)
   1085             try:
-> 1086                 return thread.result
   1087             except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)
<ipython-input-2-7302a08d5feb> in <module>
      9 
     10 c = Client(protocol='http', port_expose=5000 )  # connect to localhost:12345
---> 11 c.post('/search', Document(text='@request(on=something)'), on_done=print_matches)

/usr/local/lib/python3.9/site-packages/jina/clients/mixin.py in post(self, on, inputs, on_done, on_error, on_always, parameters, target_peapod, request_size, show_progress, continue_on_error, return_results, **kwargs)
     54                 return result
     55 
---> 56         return run_async(
     57             _get_results,
     58             inputs=inputs,

/usr/local/lib/python3.9/site-packages/jina/helper.py in run_async(func, *args, **kwargs)
   1088                 from .excepts import BadClient
   1089 
-> 1090                 raise BadClient(
   1091                     'something wrong when running the eventloop, result can not be retrieved'
   1092                 )

BadClient: something wrong when running the eventloop, result can not be retrieved

**Comment by vwoloszyn** [comment]
if I change from protocol='http' to protocol='grpc' it works fine

**Comment by hanxiao** [comment]
This should be fixed in `2.0.3`, please try `pip install -U jina`.

**Comment by vwoloszyn** [comment]
I have done, pip3 install -U "jina[standard]" and still same error when protocol='http'
