### ISSUE TITLE
Passing extra init parameters to executors does not work when `parallel>1`

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2889]
**Describe the bug**
In the following codes, when `parallel>1`, it will break. 

```python
from jina import Executor, requests, Flow, Document


class FooExecutor(Executor):
    def __init__(self, default_traversal_paths=['r'], **kwargs):
        super().__init__(**kwargs)
        self.traversal_paths = default_traversal_paths

    @requests
    def foo(self, **kwargs):
        print(f'hello')


f = Flow().add(uses=FooExecutor, parallel=3, override_with={'default_traversal_paths': ['r', 'c']})

with f:
    f.post(
        on='\index',
       inputs=[Document(text=f'hi, {i}') for i in range(3)])
```

**Describe how you solve it**

---

**Environment**
- jina 2.0.5
- jina-proto 0.0.84
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.19.5
- protobuf 3.17.0
- proto-backend cpp
- grpcio 1.34.1
- pyyaml 5.4.1
- python 3.8.5
- platform Darwin
- platform-release 19.3.0
- platform-version Darwin Kernel Version 19.3.0: Thu Jan 9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 963354756450
- session-id a806e2ae-dfd9-11eb-bd96-00e04c6b0562
- uptime 2021-07-08T18:45:48.286413
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
**Screenshots**

**Comment by JoanFM** [comment]
how does it break?

**Comment by cristianmtr** [comment]
```
/home/cristian/envs/jina/bin/python /home/cristian/.config/JetBrains/PyCharm2021.1/scratches/scratch_13.py
      pod0/head@39584[C]:can not load the executor from BaseExecutor
      pod0/head@39584[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 87, in _load_executor
    self._executor = BaseExecutor.load_config(
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 553, in load_config
    return JAML.load(tag_yml, substitute=False)
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 89, in load
    r = yaml.load(stream, Loader=JinaLoader)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 426, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(cls, data)
  File "/home/cristian/code/jina/jina/jaml/parsers/executor/legacy.py", line 69, in parse
    obj = cls(
  File "/home/cristian/code/jina/jina/executors/decorators.py", line 65, in arg_wrapper
    f = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_traversal_paths'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/peapods/peas/__init__.py", line 78, in run
    runtime = runtime_cls(
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 59, in __init__
    self._load_executor()
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 104, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
     pod0/pea-0@39574[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Podfailed to start
      pod0/tail@39591[C]:can not load the executor from BaseExecutor
      pod0/tail@39591[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 87, in _load_executor
    self._executor = BaseExecutor.load_config(
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 553, in load_config
    return JAML.load(tag_yml, substitute=False)
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 89, in load
    r = yaml.load(stream, Loader=JinaLoader)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/cristian/envs/jina/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 426, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(cls, data)
  File "/home/cristian/code/jina/jina/jaml/parsers/executor/legacy.py", line 69, in parse
    obj = cls(
  File "/home/cristian/code/jina/jina/executors/decorators.py", line 65, in arg_wrapper
    f = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_traversal_paths'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/peapods/peas/__init__.py", line 78, in run
    runtime = runtime_cls(
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 59, in __init__
    self._load_executor()
  File "/home/cristian/code/jina/jina/peapods/runtimes/zmq/zed.py", line 104, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
           Flow@39574[E]:pod0:<jina.peapods.pods.Pod object at 0x7fa38287f3d0> can not be started due to RuntimeFailToStart(), Flow is aborted
           JINA@39594[E]:all gateway tasks are cancelled
        gateway@39594[E]:Received message is empty.
Traceback (most recent call last):
  File "/home/cristian/.config/JetBrains/PyCharm2021.1/scratches/scratch_13.py", line 16, in <module>
    with f:
  File "/home/cristian/code/jina/jina/flow/base.py", line 908, in __enter__
    return self.start()
  File "/home/cristian/code/jina/jina/flow/base.py", line 953, in start
    v.wait_start_success()
  File "/home/cristian/code/jina/jina/peapods/pods/__init__.py", line 503, in wait_start_success
    p.wait_start_success()
  File "/home/cristian/code/jina/jina/peapods/peas/__init__.py", line 276, in wait_start_success
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart

Process finished with exit code 1
```

**Comment by JoanFM** [comment]
@nan-wang can u try adding *args to the init?

**Comment by nan-wang** [comment]
> can u try adding *args to the init?
The same error.

**Comment by cristianmtr** [comment]
Strange. If I add 

```python
...
class FooExecutor(Executor):
    def __init__(self, default_traversal_paths=['r'], **kwargs):
        super().__init__(**kwargs)
        print(default_traversal_paths)
        self.traversal_paths = default_traversal_paths
...
```
