### ISSUE TITLE
cannot get embedding from reloaded DocumentArrayMemmap 

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/jina#2944]
**Describe the bug**

You can reproduce the error with the following sample scripts
```python
from jina import Document
from jina.types.arrays.memmap import DocumentArrayMemmap
import numpy as np

def random_docs(num_docs):
    for j in range(num_docs):
        doc_id = j

        d = Document(id=doc_id)
        d.tags['id'] = doc_id
        
        d.embedding = np.random.random(
            [10 + np.random.randint(0, 1)]
        )
        yield d

dam = DocumentArrayMemmap('tmp_memmap_toy')
docs = list(random_docs(100))
dam.extend(docs)

dam2 = DocumentArrayMemmap('tmp_memmap_toy')
x = dam2.get_attributes('embedding')
```
The error log is:
```
Traceback (most recent call last):
  File "toys/toy_memmap.py", line 22, in <module>
    x = dam2.get_attributes('embedding')
  File "/Users/fengwang/Jina/workspace/jina/jina/types/arrays/document.py", line 62, in get_attributes
    return self.get_attributes_with_docs(*fields)[0]
  File "/Users/fengwang/Jina/workspace/jina/jina/types/arrays/document.py", line 79, in get_attributes_with_docs
    for doc in self:
  File "/Users/fengwang/Jina/workspace/jina/jina/types/arrays/memmap.py", line 208, in __iter__
    yield self[k]
  File "/Users/fengwang/Jina/workspace/jina/jina/types/arrays/memmap.py", line 160, in __getitem__
    with mmap.mmap(self._body_fileno, offset=p, length=l) as m:
ValueError: mmap length is greater than file size
```

**Describe how you solve it**

---

**Environment**

```
- jina 2.0.8                                                                                                                            
- jina-proto 0.0.84                                                                                                                     
- jina-vcs-tag (unset)                                                                                                                  
- libzmq 4.3.4                                                                                                                          
- pyzmq 1.18.1                                                                                                                          
- protobuf 3.17.3                                                                                                                       
- proto-backend cpp                                                                                                                     
- grpcio 1.38.1                                                                                                                         
- pyyaml 5.4.1                                                                                                                          
- python 3.8.3                                                                                                                          
- platform Darwin                                                                                                                       
- platform-release 20.3.0                                                                                                               
- platform-version Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101                 
- architecture x86_64                                                                                                                   
- processor i386                                                                                                                        
- uid 32988856450101                                                                                                                    
- session-id dc6b9ba2-e44d-11eb-9112-1e00d111fc35                                                                                       
- uptime 2021-07-14T10:47:42.380945                                                                                                     
- ci-vendor (unset)                                                                                                                     
* JINA_ARRAY_QUANT (unset)                                                                                                              
* JINA_CONTROL_PORT (unset)                                                                                                             
* JINA_DEFAULT_HOST (unset)                                                                                                             
* JINA_DISABLE_UVLOOP (unset)                                                                                                           
* JINA_FULL_CLI (unset)                                                                                                                 
* JINA_HUBBLE_REGISTRY (unset)                                                                                                          
* JINA_HUB_CACHE_DIR (unset)                                                                                                            
* JINA_HUB_ROOT (unset)                                                                                                                 
* JINA_LOG_CONFIG (unset)                                                                                                               
* JINA_LOG_ID (unset)                                                                                                                   
* JINA_LOG_LEVEL (unset)                                                                                                                
* JINA_LOG_NO_COLOR (unset)                                                                                                             
* JINA_LOG_WORKSPACE (unset)                                                                                                            
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)                                                                                                 
* JINA_POD_NAME (unset)                                                                                                                 
* JINA_RANDOM_PORT_MAX (unset)                                                                                                          
* JINA_RANDOM_PORT_MIN (unset)                                                                                                          
* JINA_VCS_VERSION (unset)
```
**Screenshots**

**Comment by hanxiao** [comment]
fake issue as suggested in https://jinaai.slack.com/archives/C018F60RBL5/p1626433114282100
