### ISSUE TITLE
error for embedding

### ISSUE THREAD

**Issue by yangsp5** [jina-ai/jina#3036]
I follow the cookbook and use `csr_matrix`, set  `use_scipy=False` and got wrong :
```
Traceback (most recent call last):
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 313, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 299, in _callback
    self._pre_hook(msg)._handle()._post_hook(msg)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 251, in _handle
    groundtruths_matrix=self.groundtruths_matrix,
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/executors/__init__.py", line 186, in __call__
    self, **kwargs
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/executors/decorators.py", line 103, in arg_wrapper
    return fn(*args, **kwargs)
  File "index.py", line 66, in bar
    docs.match(self._docs, metric='cosine', limit=20, use_scipy=True)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/types/arrays/neural_ops.py", line 65, in match
    dists = cdist(X, Y, metric)
  File "/opt/conda/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2931, in cdist
    raise ValueError('XA must be a 2-dimensional array.')
ValueError: XA must be a 2-dimensional array.
```

set `use_scipy=False`,  I got this wrong
```
Traceback (most recent call last):
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 313, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 299, in _callback
    self._pre_hook(msg)._handle()._post_hook(msg)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 251, in _handle
    groundtruths_matrix=self.groundtruths_matrix,
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/executors/__init__.py", line 186, in __call__
    self, **kwargs
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/executors/decorators.py", line 103, in arg_wrapper
    return fn(*args, **kwargs)
  File "index.py", line 66, in bar
    docs.match(self._docs, metric='cosine', limit=20, use_scipy=False)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/types/arrays/neural_ops.py", line 65, in match
    dists = cdist(X, Y, metric)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/math/distance.py", line 25, in cdist
    dists = cosine(x_mat, y_mat)
  File "/home/oppoer/.local/lib/python3.7/site-packages/jina/math/distance.py", line 41, in cosine
    return 1 - np.dot(x_mat, y_mat.T) / np.outer(
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (1,) and (1024,) not aligned: 1 (dim 0) != 1024 (dim 0)
```
The encode.py like this:
```
    @requests
    def encode(self, docs: DocumentArray, **kwargs):
        print(f'\n===len: {len(docs)}===\n')
        for doc in docs:
            doc.embedding = csr_matrix([0,0,0,1,0])
```

And I find that using `cosine_similarity` from `from sklearn.metrics.pairwise import cosine_similarity` is ok
```
cosine_similarity(X, Y)
```
 MAYBE YOU SHOULD CHANGE THE COOKBOOK or ADD SKLEARN IN JINA?

**Comment by davidbp** [comment]
Hello @yangsp5, `csr_matrix` is not a native type of Jina or any of the package requirements. If you want to use sparse arrays you can do it with `scipy` and it is supported using `scipy=True`. Why should sklearn be a requirement in Jina?

**Comment by yangsp5** [comment]
> Hello @yangsp5, `csr_matrix` is not a native type of Jina or any of the package requirements. If you want to use sparse arrays you can do it with `scipy` and it is supported using `scipy=True`. What is the motivation for having sklearn as a Jina requirement?
> 
> We will take a look and get back to you soon.

I change to this and set `docs.match(self._docs, metric='euclidean', limit=20, use_scipy=False)` , then sucess!!!!
```
doc.embedding = csr_matrix((values, ([0]*len(index), index)), shape=(1, self.n)).A.reshape(-1)
```

BUT, SET `docs.match(self._docs, metric='euclidean', limit=20, use_scipy=True)`  AND got wrong
```
doc.embedding = csr_matrix((values, ([0]*len(index), index)), shape=(1, self.n))
```
Like this
```
  File "/opt/conda/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2931, in cdist
    raise ValueError('XA must be a 2-dimensional array.')
ValueError: XA must be a 2-dimensional array.
```

**Comment by yangsp5** [comment]
OK, I have fixed it. Just change the metric:

```
from sklearn.metrics.pairwise import cosine_similarity
class Indexer(Executor):
    @requests(on='/search')
    def bar(self, docs: DocumentArray, **kwargs):        
         docs.match(self._docs, metric=cosine_similarity, limit=20)
```

**Comment by yangsp5** [comment]
OK, well. I have fix this by change the source code `/jina/types/arrays/neural_ops.py`:
The origin code is:
```
        # line 56
        X = np.stack(self.get_attributes('embedding'))
        Y = np.stack(darray.get_attributes('embedding'))
        limit = min(limit, len(darray))
```
And change to this:

```
        # line 55
        from scipy import sparse
        X = self.get_attributes('embedding')
        Y = darray.get_attributes('embedding')

        if isinstance(X[0], sparse.csr_matrix) or \
            isinstance(X[0], sparse.coo.coo_matrix):
            X = sparse.vstack(X)
            Y = sparse.vstack(Y)
        else:
            X = np.stack(X)
            Y = np.stack(Y)
```
And change the code
```
from sklearn.metrics.pairwise import cosine_similarity
class Indexer(Executor):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._docs = DocumentArray()

    @requests(on='/index')
    def foo(self, docs: DocumentArray, **kwargs):
        self._docs.extend(docs)

    @requests(on='/search')
    def bar(self, docs: DocumentArray, **kwargs):        
         docs.match(self._docs, metric=cosine_similarity, limit=20)
```

It runs

**Comment by davidbp** [comment]
Happy that you have it running.  What you propose is  possible but we do not have `scipy` or `sklearn` as Jina requirements, we are looking into another way to do it, allowing the user to specify scipy backend and then only using scipy operations (or creating our own distances).

**Comment by davidbp** [comment]
@yangsp5 we are working on a solution https://github.com/jina-ai/jina/pull/3041 soon there will be native support for .match with sparse embeddings without any need to install scikit-learn

**Comment by bwanglzu** [comment]
I'll reopen this issue, the will be closed automatically when PR getting merged.

**Comment by davidbp** [comment]
Dear @yangsp5, your comments have been addressed https://github.com/jina-ai/jina/pull/3097 and now the cookbook contains an example with sparse arrays and `.match`
