### ISSUE TITLE
can not run fashion demo

### ISSUE THREAD

**Issue by gojuukaze** [jina-ai/jina#3037]
**Describe the bug**

```
docker run -v "$(pwd)/j:/j" jinaai/jina hello fashion --workdir /j && open j/hello-world.html
```

I got the following error:

```
    pod0/pea-0@17[E]:ModuleNotFoundError("No module named 'PIL'")
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 313, in _msg_callback
    processed_msg = self._callback(msg)
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 299, in _callback
    self._pre_hook(msg)._handle()._post_hook(msg)
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 251, in _handle
    groundtruths_matrix=self.groundtruths_matrix,
  File "/usr/local/lib/python3.7/site-packages/jina/executors/__init__.py", line 190, in __call__
    self, **kwargs
  File "/usr/local/lib/python3.7/site-packages/jina/executors/decorators.py", line 103, in arg_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jina/helloworld/fashion/my_executors.py", line 70, in encode
    doc.convert_image_blob_to_uri(width=28, height=28)
  File "/usr/local/lib/python3.7/site-packages/jina/types/document/__init__.py", line 1029, in convert_image_blob_to_uri
    png_bytes = png_to_buffer(self.blob, width, height, resize_method)
  File "/usr/local/lib/python3.7/site-packages/jina/types/document/converters.py", line 71, in png_to_buffer
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Environment**

```
# docker images 
REPOSITORY                                                    TAG             IMAGE ID       CREATED         SIZE
jinaai/jina                                                   latest          3ff147311047   19 hours ago    234MB

# docker run jinaai/jina -v 
2.0.12
```

**Screenshots**

**Comment by bwanglzu** [comment]
hi @gojuukaze thanks for reporting this, seems #3049 is going to fix this.

**Comment by bwanglzu** [comment]
i checked the latest jina, now it's working. @gojuukaze fell free to create an issue and ask other questions, I'll close it for now.
