### ISSUE TITLE
Can not fetch the URL of Hubble from `api.jina.ai`

### ISSUE THREAD

**Issue by snehampatil** [jina-ai/jina#3217]
**Describe the bug**
I was trying out the **Semantic Wikipedia Search with Transformers and DistilBERT example.** 
This is the error I am getting after running

```
python3 app.py -t index
```

    Fetching meta data of TransformerTorchEncoder...           JINA@5197[C]:Can not fetch the URL of Hubble from `api.jina.ai`
              HubIO@5197[E]:Error while pulling jinahub+docker://TransformerTorchEncoder: 
    JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
    Traceback (most recent call last):
      File "app.py", line 90, in <module>
        main()
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
        return self.main(*args, **kwargs)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/click/core.py", line 1062, in main
        rv = self.invoke(ctx)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
        return __callback(*args, **kwargs)
      File "app.py", line 84, in main
        index(num_docs)
      File "app.py", line 46, in index
        with flow:
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/flow/base.py", line 930, in __enter__
        return self.start()
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/flow/base.py", line 970, in start
        self.enter_context(v)
      File "/usr/lib/python3.8/contextlib.py", line 425, in enter_context
        result = _cm_type.__enter__(cm)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/peapods/pods/__init__.py", line 186, in __enter__
        return self.start()
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/peapods/pods/__init__.py", line 496, in start
        self._enter_pea(BasePea(_args))
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 127, in __init__
        self.runtime_cls = self._get_runtime_cls()
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 378, in _get_runtime_cls
        self.args.uses = HubIO(
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/hubble/hubio.py", line 707, in pull
        raise e
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/hubble/hubio.py", line 641, in pull
        executor = HubIO._fetch_meta(name, tag=tag, secret=secret)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/hubble/helper.py", line 280, in wrapper
        result = func(*args, **kwargs)
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/hubble/hubio.py", line 559, in _fetch_meta
        pull_url = get_hubble_url() + f'/{name}/?'
      File "/home/sneha/Downloads/env/lib/python3.8/site-packages/jina/hubble/helper.py", line 39, in get_hubble_url
        u = json.load(resp)['url']
      File "/usr/lib/python3.8/json/__init__.py", line 293, in load
        return loads(fp.read(),
      File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    **Environment**

```
- jina 2.0.18
- jina-proto 0.0.85
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.2
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.39.0
- pyyaml 5.4.1
- python 3.8.10
- platform Linux
- platform-release 5.8.0-43-generic
- platform-version #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021
- architecture x86_64
- processor x86_64
- uid 118502958162605
- session-id 446121fd-00ad-11ec-95ce-6bc71eb9e2ad
- uptime 2021-08-19T10:51:11.580160
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_MP_START_METHOD (unset)

```

How can this be solved?

**Comment by mapleeit** [comment]
Hi @snehampatil Thanks for reporting. Do you use any VPN or proxy? 

And what did it say if your open this url on your browser? `https://api.jina.ai/hub/hubble.json`

**Comment by snehampatil** [comment]
Hello @mapleeit 
Thanks for your reply

I am not using any VPN.

When I open this url https://api.jina.ai/hub/hubble.json, this is what I get

![sss1](https://user-images.githubusercontent.com/68156719/130637909-8e10932a-61b9-4463-a6c1-fbaff63fdd39.png)


And with this one http://k8s-prod-hubble-8915a76777-762046330.us-west-2.elb.amazonaws.com/

![sss2](https://user-images.githubusercontent.com/68156719/130638125-ba6b63f2-d261-4240-9d02-a96b84b9b4db.png)

**Comment by mapleeit** [comment]
Weird. I thought it's was network issue. But you can access it via browser.

Related code is here: https://github.com/jina-ai/jina/blob/master/jina/hubble/helper.py#L35

Do you mind print some logs here and to see what the problem it is? I tried to reproduce, but unfortunately I can't get the same result as you.

**Comment by snehampatil** [comment]
Please excuse me for the late reply.

I had reinstalled the examples and when I tried to run ```python3 app.py -t index```:
```
Pulling from jinahub/u9pqs8eb
    transformer@3981[E]:can not find local image: jinahub/u9pqs8eb:v19-2.0.18
    transformer@3981[W]:pulling jinahub/u9pqs8eb:v19-2.0.18, this could take a while. if you encounter timeout error due to pulling takes to long, then please set "timeout-ready" to a larger value.
    transformer@3801[W]:<class 'jina.peapods.runtimes.container.ContainerRuntime'> timeout after waiting for 600000ms, if your executor takes time to load, you may increase --timeout-ready
    transformer@3801[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
    transformer@3801[W]:Terminating process after waiting for readiness signal for graceful shutdown
    transformer@3801[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
    transformer@3801[W]:Terminating process after waiting for readiness signal for graceful shutdown
           Flow@3801[E]:transformer:<jina.peapods.pods.Pod object at 0x7ff81de62e20> can not be started due to TimeoutError('jina.peapods.peas.BasePea:transformer can not be initialized after 600000.0ms'), Flow is aborted
```
Is there any issue with the Docker?
Do I need to install any specific version?

**Comment by mapleeit** [comment]
This means it still can't pull this docker image `jinahub/u9pqs8eb:v19-2.0.18` after 10 mins(default timeout). Download speed is too slow. 

Can you try to download this image by running `docker pull jinahub/u9pqs8eb:v19-2.0.18` and have a look at the download speed? How long will it take.

If you want, you can join our slack channel. And we can have a direct conversation, because I think it's mostly the network issue. So maybe that can make us both easier.

**Comment by mapleeit** [comment]
No response since last time. Close it for now. Feel free to reopen it if have further problem.
