### ISSUE TITLE
`require_attr` in `DocumentArray.batch` does not work for `blob`

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#3450]
**Describe the bug**
```python
from jina import Document, DocumentArray
import numpy as np

docs = DocumentArray([Document(blob=np.random.random(10)) for i in range(10)])

for b in docs.batch(batch_size=3, traversal_paths=['r'], require_attr='blob'):
    print(b)
```

The above codes lead to the error

```bash
Traceback (most recent call last):
  File "/Users/nanwang/Codes/jina-ai/jina/toys/toy17.py", line 9, in <module>
    for b in docs.batch(batch_size=3, traversal_paths=['r'], require_attr='blob'):
  File "/Users/nanwang/Codes/jina-ai/jina/jina/types/arrays/traversable.py", line 132, in batch
    if getattr(d, require_attr):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Describe how you solve it**

---

**Environment**
```output
- jina 2.1.3
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.19.5
- protobuf 3.17.0
- proto-backend cpp
- grpcio 1.37.1
- pyyaml 5.4.1
- python 3.8.5
- platform Darwin
- platform-release 20.6.0
- platform-version Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT
  2021; root:xnu-7195.141.2~5/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 190070690681122
- session-id 9e83b592-1a83-11ec-8f6f-acde48001122
- uptime 2021-09-21T10:28:33.790582
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_MP_START_METHOD (unset)
```

**Screenshots**

**Comment by JoanFM** [comment]
I guess it should be changed to:

```python
if getattr(d, require_attr) is not None:
```

**Comment by tadejsv** [comment]
@JoanFM the problem here is with how empty attributes are returned. For example
```python
from jina import Document
d = Document()
d.text  # returns ''
```

and same for `uri`. For `tags` you get an empty `StructView`.
