### ISSUE TITLE
Kubernetes - NotImplementedError in K8sPod.host

### ISSUE THREAD

**Issue by saurav1869** [jina-ai/jina#3487]
Hey everyone,

I was trying to run an example from this [Jina on Kubernetes page](https://docs.jina.ai/advanced/experimental/kubernetes/#clip-image-encoder). I am unable to start the server. I am getting this error every time.

```
start_executor0@145557[I]:🏝️     Create Namespace "test-flow" for "executor0"
start_executor0@145557[I]:🔁    namespaces "test-flow" already exists
deploy_executor0@145557[I]:🔋   Create Service for "executor0" with image "executor0" pulling from "jinahub/0hnlmu3q:v61-2.1.3"
deploy_executor0@145557[I]:🔁   services "executor0" already exists 
deploy_executor0@145557[I]:🐳   Create Deployment for "jinahub/0hnlmu3q:v61-2.1.3" with replicas 1 and init_container False
deploy_executor0@145557[I]:🔁   deployments.apps "executor0" already exists
  start_gateway@145557[I]:🏝️     Create Namespace "test-flow" for "gateway"
  start_gateway@145557[I]:🔁    namespaces "test-flow" already exists
 deploy_gateway@145557[I]:🔋    Create Service for "gateway" with image "gateway" pulling from "jinaai/jina:2.1.3-py38-standard"
 deploy_gateway@145557[I]:🔁    services "gateway" already exists
 deploy_gateway@145557[I]:🐳    Create Deployment for "jinaai/jina:2.1.3-py38-standard" with replicas 1 and init_container False
 deploy_gateway@145557[I]:🔁    deployments.apps "gateway" already exists
Exception in thread Thread-4:                                                                        
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/shanus/.local/share/virtualenvs/jina/lib/python3.8/site-packages/jina/flow/base.py", line 1494, in _get_address_table
    + colored(f'{self.host}:{self.port_expose}', 'cyan', attrs='underline'),
  File "/home/shanus/.local/share/virtualenvs/jina/lib/python3.8/site-packages/jina/flow/base.py", line 1448, in host
    return self._pod_nodes[GATEWAY_NAME].host
  File "/home/shanus/.local/share/virtualenvs/jina/lib/python3.8/site-packages/jina/peapods/pods/k8s.py", line 72, in host
    raise NotImplementedError
NotImplementedError
```
I changed the below line to return `self.args.host` which allows the server to start but still client doesn't work as expected.
https://github.com/jina-ai/jina/blob/e6da08f78267101ea7b1e68c1cd562e4e56ec33b/jina/peapods/pods/k8s.py#L69

The documentation is very clear but let me know if I overlooked some important detail.

Jina version - 2.1.3

Thanks :)

**Comment by JoanFM** [comment]
Hello @saurav1869 ,

this error has been removed in a recent PR #3479, but this error should be harmless and the Flow should have started with no problem.

**Comment by saurav1869** [comment]
Hi @JoanFM, Thanks for replying. Yes, it works :+1:
