### ISSUE TITLE
Error : receive an empty stream from the client! please check your client's inputs, you can use "Client.check_input(inputs)

### ISSUE THREAD

**Issue by imvansh25** [jina-ai/jina#3522]
**Describe the bug**
Getting above mentioned error while trying to find k- simmilar images

**Describe how you solve it**

**app.py**
```
import os
from pathlib import Path

from jina import Flow
from jina.parsers.helloworld import set_hw_parser

from helper import download_data,index_generator,query_generator
from myexecuter import MyEncoder,MyIndexer

def bestmatch():
    ## driver function
    targets = download_data()
    
    f = (
        Flow()
        .add(uses=MyEncoder, parallel=2)
        .add(uses=MyIndexer, workspace=os.getcwd())
    )
    print(targets)

    # run it!
    with f:
        f.index(
            index_generator(targets),
            show_progress=True,
        )
        # print(targets['data'])

        f.post(
            '/eval',
            query_generator(
                num_docs=15, target=targets
            ),
            shuffle=True,
            on_done=print_result,
            parameters={'top_k': 1},
            show_progress=True,
        )

        # write result to html
        # write_html(os.path.join(args.workdir, 'demo.html'))


def print_result(resp):
    
    for d in resp.docs:
        print(d.content)



if __name__ == '__main__':
    bestmatch()
```

**helper.py**

```
from io import BytesIO
import os
import glob
import gzip
import os
import random
import urllib.request
import webbrowser
from collections import defaultdict

import numpy as np

from jina import Document
# from jina.helper import colored
# from jina.logging.predefined import default_logger
# from jina.logging.profile import ProgressBar

import  requests
from PIL import Image
import math
import PIL
import re
import numpy as np

def download_data():
    images = []
    labels = []
    for tags in glob.glob("tax_invoices2/*"):
        label = tags.split("/")[-1]
        for img in glob.glob(tags+"/*"):
            data = np.asarray(Image.open(img).convert("RGB"), dtype=np.float32) / 255
            images.append(data)
            labels.append(label)
    return {"data":images,"labels":labels}


def index_generator(targets):
    for id_no, image in enumerate(targets['data']):
        d = Document(content = image)
        d.tags['id'] = id_no+1
        # print(d)
        yield d

def query_generator(num_docs,targets):
    for _ in range(num_docs):
        idx = random.randint(0, len(targets['data']) - 1)
        d = Document(content=targets['data'][idx])
        print(d)
        yield d
```
   
**my executer.py**

```
from typing import Dict

import numpy as np
from jina import Executor, DocumentArray, requests
from jina.types.arrays.memmap import DocumentArrayMemmap


class MyIndexer(Executor):
    """
    Executor with basic exact search using cosine distance
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._docs = DocumentArrayMemmap(self.workspace + '/indexer')

    @requests(on='/index')
    def index(self, docs: 'DocumentArray', **kwargs):
        """Extend self._docs

        :param docs: DocumentArray containing Documents
        :param kwargs: other keyword arguments
        """
        self._docs.extend(docs)

    @requests(on=['/search', '/eval'])
    def search(self, docs: 'DocumentArray', parameters: Dict, **kwargs):
        """Append best matches to each document in docs

        :param docs: documents that are searched
        :param parameters: dictionary of pairs (parameter,value)
        :param kwargs: other keyword arguments
        """
        docs.match(
            self._docs,
            metric='cosine',
            normalization=(1, 0),
            limit=int(parameters['top_k']),
        )


class MyEncoder(Executor):
    """
    Encode data using SVD decomposition
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        np.random.seed(1337)
        # generate a random orthogonal matrix
        H = np.random.rand(784, 64)
        u, s, vh = np.linalg.svd(H, full_matrices=False)
        self.oth_mat = u @ vh

    @requests
    def encode(self, docs: 'DocumentArray', **kwargs):
        """Encode the data using an SVD decomposition

        :param docs: input documents to update with an embedding
        :param kwargs: other keyword arguments
        """
        # reduce dimension to 50 by random orthogonal projection
        content = np.stack(docs.get_attributes('content'))
        print(content)
        content = content[:, :, :, 0].reshape(-1, 784)
        embeds = (content / 255) @ self.oth_mat
        for doc, embed, cont in zip(docs, embeds, content):
            doc.embedding = embed
            doc.content = cont
            doc.convert_image_blob_to_uri(width=28, height=28)
            doc.pop('blob')


```

---

**Environment**
jina --version-full
- jina 2.1.2
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.19.5
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.39.0
- pyyaml 5.3.1
- python 3.8.10
- platform Linux
- platform-release 5.11.0-27-generic
- platform-version #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
- architecture x86_64
- processor x86_64
- uid 54727434929009
- session-id 50b1832f-213c-11ec-8d7e-31c639518371
- uptime 2021-09-29T21:15:45.394080
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_MP_START_METHOD (unset)

**Screenshots**
![image](https://user-images.githubusercontent.com/44816642/135303549-0be6f6b3-9a41-4bf8-91bb-4f41cd8983c6.png)

**Comment by imvansh25** [comment]
Hey @JoanFM ,
Yes the document is getting printed.
Please elaborate on suggested checks.

**Comment by JoanFM** [comment]
Hey @imvansh25 ,

First issue I see is that `query_generator` receives a wrong kwarg, is `targets` and not `target`. If there is another issue I cannot tell because I do not have access to the data in `download_data`

**Comment by imvansh25** [comment]
hi @JoanFM , made some changes in the code based on your inputs. got this error now.

```
⠸      ERROR ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:08 0.1 step/s Traceback (most recent call last):
  File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/base/grpc.py", line 49, in _get_results
    async for resp in stub.Call(req_iter):
  File "/home/vansh/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 321, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/vansh/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 231, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode"
        debug_error_string = "{"created":"@1632996102.318721046","description":"Error received from peer ipv4:0.0.0.0:60219","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vansh/Desktop/Jina-Ai/invoiceSearch/myapp.py", line 52, in <module>
    bestmatch()
  File "/home/vansh/Desktop/Jina-Ai/invoiceSearch/myapp.py", line 23, in bestmatch
    f.index(
  File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/mixin.py", line 60, in post
    return run_async(
  File "/home/vansh/.local/lib/python3.8/site-packages/jina/helper.py", line 1205, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/mixin.py", line 53, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/base/grpc.py", line 90, in _get_results
    raise BadClient(msg) from rpc_ex
jina.excepts.BadClient: gRPC error: StatusCode.UNKNOWN Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode
```

**Comment by imvansh25** [comment]
@JoanFM  Also, can you please help in finding out the following problem:-
1. How does Jina support cloud storage like AWS and GCP.
2. How to handle million's  of images in Jina AI.

**Comment by JoanFM** [comment]
> hi @JoanFM , made some changes in the code based on your inputs. got this error now.
> 
> ```
> ⠸      ERROR ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:08 0.1 step/s Traceback (most recent call last):
>   File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/base/grpc.py", line 49, in _get_results
>     async for resp in stub.Call(req_iter):
>   File "/home/vansh/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 321, in _fetch_stream_responses
>     await self._raise_for_status()
>   File "/home/vansh/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 231, in _raise_for_status
>     raise _create_rpc_error(await self.initial_metadata(), await
> grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode"
>         debug_error_string = "{"created":"@1632996102.318721046","description":"Error received from peer ipv4:0.0.0.0:60219","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode","grpc_status":2}"
> >
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/vansh/Desktop/Jina-Ai/invoiceSearch/myapp.py", line 52, in <module>
>     bestmatch()
>   File "/home/vansh/Desktop/Jina-Ai/invoiceSearch/myapp.py", line 23, in bestmatch
>     f.index(
>   File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/mixin.py", line 60, in post
>     return run_async(
>   File "/home/vansh/.local/lib/python3.8/site-packages/jina/helper.py", line 1205, in run_async
>     return asyncio.run(func(*args, **kwargs))
>   File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/mixin.py", line 53, in _get_results
>     async for resp in c._get_results(*args, **kwargs):
>   File "/home/vansh/.local/lib/python3.8/site-packages/jina/clients/base/grpc.py", line 90, in _get_results
>     raise BadClient(msg) from rpc_ex
> jina.excepts.BadClient: gRPC error: StatusCode.UNKNOWN Unexpected <class 'TypeError'>: None has type NoneType, but expected one of: bytes, unicode
> ```

Can u share the changed code?

**Comment by imvansh25** [comment]
PS : here i am only testing **f.index**.

**app.py**

```
import os
from pathlib import Path

from jina import Flow
from jina.parsers.helloworld import set_hw_parser

from helper import download_data,index_generator,query_generator
from myexecuter import MyEncoder,MyIndexer

def bestmatch():
    ## driver function
    
    
    f = (
        Flow()
        .add(uses=MyEncoder, parallel=2)
        .add(uses=MyIndexer, workspace=os.getcwd())
    )
    

    # run it!
    with f:
        f.index(
            index_generator(),
            show_progress=True,
        )
        print("done")

        # f.post(
        #     '/eval',
        #     query_generator(
        #         num_docs=15, targets=targets
        #     ),
        #     shuffle=True,
        #     on_done=print_result,
        #     parameters={'top_k': 1},
        #     show_progress=True,
        # )

        # write result to html
        # write_html(os.path.join(args.workdir, 'demo.html'))


def print_result(resp):
    
    for d in resp.docs:
        print(d.content)



if __name__ == '__main__':
    bestmatch()
```

**helper.py**

```
from io import BytesIO
import os
import glob
import gzip
import os
import random
import urllib.request
import webbrowser
from collections import defaultdict

import numpy as np

from jina import Document
# from jina.helper import colored
# from jina.logging.predefined import default_logger
# from jina.logging.profile import ProgressBar

import  requests
from PIL import Image
import math
import PIL
import re
import numpy as np
import cv2
def download_data():
    images = []
    labels = []
    for tags in glob.glob("tax_invoices2/*"):
        label = tags.split("/")[-1]
        for img in glob.glob(tags+"/*"):
            data = np.asarray(Image.open(img).convert("RGB"), dtype=np.float32) / 255
            
            images.append(data)
            labels.append(label)
    return {"data":images,"labels":labels}


def index_generator():
    images = []
    labels = []
    id_no = 0
    for tags in glob.glob("tax_invoices2/*"):
        label = tags.split("/")[-1]
        for img in glob.glob(tags+"/*"):
            print(img)
            data = cv2.imread(img)
            d = Document(content = data)
            d.tags['id'] = id_no+1
            # print(id_no,targets['labels'][id_no])
            
            id_no+=1
            yield d

def query_generator(num_docs,targets):
    for _ in range(num_docs):
        idx = random.randint(0, len(targets['data']) - 1)
        d = Document(content=targets['data'][idx])
        print(d)
        yield d
```
**executer.py**
```
from typing import Dict

import numpy as np
from jina import Executor, DocumentArray, requests
from jina.types.arrays.memmap import DocumentArrayMemmap


class MyIndexer(Executor):
    """
    Executor with basic exact search using cosine distance
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._docs = DocumentArrayMemmap(self.workspace + '/indexer')

    @requests(on='/index')
    def index(self, docs: 'DocumentArray', **kwargs):
        """Extend self._docs

        :param docs: DocumentArray containing Documents
        :param kwargs: other keyword arguments
        """
        self._docs.extend(docs)

    @requests(on=['/search', '/eval'])
    def search(self, docs: 'DocumentArray', parameters: Dict, **kwargs):
        """Append best matches to each document in docs

        :param docs: documents that are searched
        :param parameters: dictionary of pairs (parameter,value)
        :param kwargs: other keyword arguments
        """
        docs.match(
            self._docs,
            metric='cosine',
            normalization=(1, 0),
            limit=int(parameters['top_k']),
        )


class MyEncoder(Executor):
    """
    Encode data using SVD decomposition
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        np.random.seed(1337)
        # generate a random orthogonal matrix
        H = np.random.rand(784, 64)
        u, s, vh = np.linalg.svd(H, full_matrices=False)
        self.oth_mat = u @ vh

    @requests
    def encode(self, docs: 'DocumentArray', **kwargs):
        """Encode the data using an SVD decomposition

        :param docs: input documents to update with an embedding
        :param kwargs: other keyword arguments
        """
        # reduce dimension to 50 by random orthogonal projection
        content = np.stack(docs.get_attributes('content'))
        print(content)
        content = content[:, :, :, 0].reshape(-1, 784)
        embeds = (content / 255) @ self.oth_mat
        for doc, embed, cont in zip(docs, embeds, content):
            doc.embedding = embed
            doc.content = cont
            doc.convert_image_blob_to_uri(width=28, height=28)
            doc.pop('blob')
```

**Comment by JoanFM** [comment]
Hello @imvansh25 ,

Would it be possible for you to share some small example of ur data and the structure of the project? I am not sure what is the index generator trying to do
