### ISSUE TITLE
Resource temporarily unavailable: '/home/kavan/.jina/disk_cache.db' when you run flow in thread 

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/jina#3617]
When i try to run flow in multiple threads then i'm getting this error

```
        encoder@13543[E]:Error while pulling jinahub://TransformerSentenceEncoder: 
FileNotFoundError(2, 'No such file or directory')
        encoder@13543[E]:Error while pulling jinahub://TransformerSentenceEncoder: 
FileNotFoundError(2, 'No such file or directory')
        encoder@13543[E]:Error while pulling jinahub://TransformerSentenceEncoder: 
FileNotFoundError(2, 'No such file or directory')
        encoder@13543[E]:Error while pulling jinahub://TransformerSentenceEncoder: 
FileNotFoundError(2, 'No such file or directory')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/hubble/helper.py", line 285, in wrapper
    cache_db = shelve.open(
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/kavan/.jina/disk_cache.db'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/media/kavan/WORK/Job/jina_rnd/main.py", line 13, in encode
    with self.flow:
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/flow/base.py", line 1097, in __enter__
    return self.start()
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/flow/base.py", line 1141, in start
    self.enter_context(v)
  File "/usr/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/peapods/pods/__init__.py", line 186, in __enter__
    return self.start()
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/peapods/pods/__init__.py", line 499, in start
    self._enter_pea(BasePea(_args))
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 132, in __init__
    self.runtime_cls = self._get_runtime_cls()
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 377, in _get_runtime_cls
    update_runtime_cls(self.args)
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/peapods/peas/helper.py", line 106, in update_runtime_cls
    _args.uses = HubIO(_hub_args).pull()
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/hubble/hubio.py", line 767, in pull
    raise e
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/hubble/hubio.py", line 678, in pull
    executor = HubIO.fetch_meta(name, tag, secret=secret, force=need_pull)
  File "/media/kavan/WORK/Job/jina_rnd/venv/lib/python3.8/site-packages/jina/hubble/helper.py", line 291, in wrapper
    os.remove(cache_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kavan/.jina/disk_cache.db'
Environment

- jina 2.1.6
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.19.5
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.38.0
- pyyaml 5.4.1
- python 3.8.10
- platform Linux
- platform-release 5.11.0-37-generic
- platform-version #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021
- architecture x86_64
- processor x86_64
- uid 197692621127665
- session-id d0787ac3-2835-11ec-aa16-b3cce674fff1
- uptime 2021-10-08T18:16:53.356043
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_MP_START_METHOD (unset)
```
Reproduce an issue:-

```
from jina import Flow, Document


class RemoteJina:
    def __init__(self, **kwargs):
        self.flow = Flow().add(
            name='encoder',
            uses=kwargs.pop('executor'),
            uses_with=kwargs
        )

    def encode(self, text):
        with self.flow:
            return self.flow.index(
                Document(content=text),
                request_size=len(text),
                return_results=True
            )


jina_config = {
    'executor': 'jinahub://TransformerSentenceEncoder',
    'device': 'cpu',
    'model_name': 'sentence-transformers/LaBSE'
}

obj1 = RemoteJina(**jina_config)
obj2 = RemoteJina(**jina_config)
obj3 = RemoteJina(**jina_config)
obj4 = RemoteJina(**jina_config)

```
from threading import Thread

```
t1 = Thread(target=obj1.encode, args=('hello, i am pillo',))
t2 = Thread(target=obj2.encode, args=('hello, i am mike',))
t3 = Thread(target=obj3.encode, args=('hello, i am pillo',))
t4 = Thread(target=obj4.encode, args=('hello, i am mike',))

t1.start()
t2.start()
t3.start()
t4.start()

t1.join()
t2.join()
t3.join()
t4.join()
```

**Comment by JoanFM** [comment]
Hello @Kavan72 ,

Thanks for reporting this issue. May I ask what is the ultimate intention of this code? Why do not use the Flow with the `parallelized` encoders?

**Comment by JoanFM** [comment]
Thanks, currently our caching mechanism in `hubble` helper does not lock the `cache` file. Would u be able to provide a fix by providing a global file lock for the cache file?

**Comment by Kavan72** [comment]
i guess, Race condition is happening here like each thread is trying to access that lock file at a same time.

**Comment by hanxiao** [comment]
i can't reproduce in #3620 

> > i guess, Race condition is happening here like each thread is trying to access that lock file at a same time.
> 
> Exactly, that is the case.

**Comment by Kavan72** [comment]
try to delete `.jina` dir from home and then try

**Comment by hanxiao** [comment]
> try to delete .jina dir from home and then try

i still can't reproduce, tho they did throw errors but the errors are different than yours. Let me ask our team to reproduce and confirm.

**Comment by JoanFM** [comment]
Hello @Kavan72 do you plan to work on this?

**Comment by JoanFM** [comment]
> @JoanFM i can work on this issue. can you suggest what is the best approach for this

Hey @Kavan72, sorry for the delay in the response. I think usinf FileLock on the hubble cache file should be enough.

**Comment by Kavan72** [comment]
@CatStark sorry, I was on vacation, I'll work on this issue in next weekend

**Comment by JoanFM** [comment]
Hey @Kavan72,

Dis u have any time to work on it?

**Comment by Kavan72** [comment]
@JoanFM I've created pr. please give some feedback.
