### ISSUE TITLE
Using a torch model on GPU in Executor fails

### ISSUE THREAD

**Issue by matthewfranglen** [jina-ai/jina#3849]
**Describe the bug**

If I load the CLIP model onto the graphics card then the creation of the executor fails with the error message

> RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

Here is some code that reproduces the error:

```python
import clip
from jina import Document, DocumentArray, Executor, Flow, requests


class ClipEmbedding(Executor):
    def __init__(self, model: str = "ViT-B/32", device: str = "cpu", **kwargs) -> None:
        super().__init__(**kwargs)
        self.model, self.preprocess = clip.load(model, device=device)
        self.model.eval()
        self.device = device

    @requests
    def act(self, docs: DocumentArray, **kwargs) -> None:
        pass


flow = Flow().add(name="embed", uses=ClipEmbedding, uses_with={"device": "cuda"})
with flow:
    flow.index(inputs=Document(uri="/some/path"))
```

The full stack trace is

```
⠋ 0/2 waiting embed gateway to be ready...DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/grpc/aio/_server.py:54)
⠇ 1/2 waiting embed to be ready...          embed@4073179[C]:can not load the executor from ClipEmbedding
          embed@4073179[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 72, in _load_executor
    self._executor = BaseExecutor.load_config(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/jaml/__init__.py", line 612, in load_config
    return JAML.load(tag_yml, substitute=False)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/jaml/__init__.py", line 90, in load
    r = yaml.load(stream, Loader=JinaLoader)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/jaml/__init__.py", line 452, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(cls, data)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/jaml/parsers/executor/legacy.py", line 69, in parse
    obj = cls(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/executors/decorators.py", line 65, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/embed.py", line 8, in __init__
    self.model, self.preprocess = clip.load(model, device=device)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/clip/clip.py", line 134, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/torch/cuda/__init__.py", line 204, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/peas/__init__.py", line 79, in run
    runtime = runtime_cls(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 72, in __init__
    self._data_request_handler = DataRequestHandler(self.args, self.logger)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 67, in __init__
    self._load_executor()
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 91, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
           Flow@4073132[E]:Flow is aborted due to ['embed'] can not be started.
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
Traceback (most recent call last):
  File "/home/matthew/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/matthew/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/embed.py", line 18, in <module>
    with flow:
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/flow/base.py", line 1118, in __enter__
    return self.start()
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/flow/base.py", line 1167, in start
    self._wait_until_all_ready()
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/flow/base.py", line 1251, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Environment**
- jina 2.2.2
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.3
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.41.1
- pyyaml 6.0
- python 3.9.6
- platform Linux
- platform-release 5.4.0-89-generic
- platform-version #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021
- architecture x86_64
- processor x86_64
- uid 158278743441692
- session-id 28ba0c2b-3bcb-11ec-9b07-8ff42447411c
- uptime 2021-11-02T10:53:48.795908
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Comment by matthewfranglen** [comment]
I found this issue: #2691 which appears related however a fix was merged for that and the issue was closed in July. I believe that I am using the latest version of Jina which was released yesterday

**Comment by deepankarm** [comment]
@matthewfranglen, could you try starting the Flow via an explicit function call inside `if __name__ == '__main__'`. [Here's an example.](https://docs.jina.ai/advanced/experimental/windows/#explicit-entrypoint)

**Comment by matthewfranglen** [comment]
I am on linux btw. I will try your suggestions. Thank you for the fast response!

**Comment by matthewfranglen** [comment]
I can confirm that using `JINA_MP_START_METHOD=spawn` allows the GPU model to run successfully. I'm closing this ticket because you already have a fix for this problem.

Is this documented somewhere?

**Comment by JoanFM** [comment]
Hey @matthewfranglen,

We realized this documentation is missing and we are working on adding this. Thank you for reporting and do not hesitate to ask for any question or open more tickets

**Comment by deepankarm** [comment]
@matthewfranglen Thank you so much for raising & closing this. Now [we have a section](https://docs.jina.ai/fundamentals/flow/remarks/#multiprocessing-spawn) in our docs which explains the caveats while using Jina with spawn.

**Comment by matthewfranglen** [comment]
Thank you, that's really great. Including the error message will help a lot when searching for this too.
