### ISSUE TITLE
Replica usage in a Flow leads to the wrong Executor class being created

### ISSUE THREAD

**Issue by matthewfranglen** [jina-ai/jina#3854]
**Describe the bug**

I have written executors to deal with composite documents, as well as documents with matches. As part of this I extracted the traversal of the sub documents into a base executor class, and then implemented the behaviour in a subclass. If I use the executor without replicating it then it works fine. If I apply replication to it then it appears that the created executor is actually the parent class.

```python
from jina import Document, Executor, Flow, requests


class BaseExecutor(Executor):
    @requests
    def act(self, **kwargs) -> None:
        self.subclass_act()

    def subclass_act(self) -> None:
        raise NotImplementedError()


class ImplementedExecutor(BaseExecutor):
    def subclass_act(self) -> None:
        print("woo")


if __name__ == "__main__":
    print("without replication")
    flow = Flow().add(name="embed", uses=ImplementedExecutor)
    with flow:
        flow.index(inputs=Document(uri="/some/path"))

    print("with replication")
    flow = Flow().add(name="embed", uses=ImplementedExecutor, replicas=4)
    with flow:
        flow.index(inputs=Document(uri="/some/path"))
```

This produces the output:

```
without replication
⠋ 0/2 waiting embed gateway to be ready...DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/grpc/aio/_server.py:54)
           Flow@360080[I]:🎉 Flow is ready to use!
        🔗 Protocol:            GRPC
        🏠 Local access:        0.0.0.0:49177
        🔒 Private network:     192.168.1.54:49177
        🌐 Public address:      81.2.75.20:49177
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/grpc/aio/_call.py:374)
woo
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
with replication
⠋ 0/2 waiting embed gateway to be ready...DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/grpc/aio/_server.py:54)
           Flow@360080[I]:🎉 Flow is ready to use!
        🔗 Protocol:            GRPC
        🏠 Local access:        0.0.0.0:37875
        🔒 Private network:     192.168.1.54:37875
        🌐 Public address:      81.2.75.20:37875
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/grpc/aio/_call.py:374)
     embed/head@360165[E]:NotImplementedError()
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 221, in _handle
    self._data_request_handler.handle(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 148, in handle
    r_docs = self._executor(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/executors/__init__.py", line 199, in __call__
    return self.requests[__default_endpoint__](
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/executors/decorators.py", line 105, in arg_wrapper
    return fn(*args, **kwargs)
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/test.py", line 7, in act
    self.subclass_act()
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/test.py", line 10, in subclass_act
    raise NotImplementedError()
NotImplementedError
woo
     embed/tail@360170[E]:NotImplementedError()
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/zmq/zed.py", line 221, in _handle
    self._data_request_handler.handle(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 148, in handle
    r_docs = self._executor(
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/executors/__init__.py", line 199, in __call__
    return self.requests[__default_endpoint__](
  File "/home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/executors/decorators.py", line 105, in arg_wrapper
    return fn(*args, **kwargs)
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/test.py", line 7, in act
    self.subclass_act()
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/test.py", line 10, in subclass_act
    raise NotImplementedError()
NotImplementedError
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10. (raised from /home/matthew/.cache/pypoetry/virtualenvs/jina-evaluation-DmTHuU_d-py3.9/lib/python3.9/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py:61)
```

The significant part of this being:

```
  File "/home/matthew/Programming/Python/jina-evaluation/src/image_search/executors/test.py", line 10, in subclass_act
    raise NotImplementedError()
NotImplementedError
```

What makes this odd is that _woo_ is printed twice. This suggests that replication sometimes creates the base class?
I added the following constructor to the base class to help describe this:

```python
def __init__(self, **kwargs) -> None:
    super().__init__(**kwargs)
    print(f"My name is {id(self)} {self.__class__.__name__}")
```

And the following output was observed (truncated the irrelevant stuff):

```
without replication
My name is 139919236181536 ImplementedExecutor
woo
with replication
My name is 139919217413904 BaseExecutor
My name is 139919217413568 ImplementedExecutor
My name is 139919216838832 ImplementedExecutor
My name is 139919216945376 ImplementedExecutor
My name is 139919216947600 BaseExecutor
woo
```

Which is quite odd indeed - apparently 5 executors were created? The id of every one seems to be distinct.

When I look at the [documentation for replicas](https://docs.jina.ai/fundamentals/flow/topology/#scale-executors-by-using-replicas) the visualized flow shows the same number of executors as the parameter to the add method. It also seems that both BaseExecutors are being invoked as the exception is thrown twice.

**Environment**

- jina 2.2.2
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.3
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.41.1
- pyyaml 6.0
- python 3.9.6
- platform Linux
- platform-release 5.4.0-89-generic
- platform-version #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021
- architecture x86_64
- processor x86_64
- uid 158278743441692
- session-id 84aea723-3bfb-11ec-9b07-8ff42447411c
- uptime 2021-11-02T16:39:58.899201
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Comment by matthewfranglen** [comment]
Using the traversal code as a mixin works:

```python
from jina import Document, DocumentArray, Executor, requests


class TraverseDocumentMixin:
    @requests
    def act(self, docs: DocumentArray, **kwargs) -> None:
        for document in docs:
            self._recurse(document, **kwargs)

    def _recurse(self, document: Document, **kwargs) -> None:
        self.update(document, **kwargs)
        for child_document in document.chunks:
            self._recurse(child_document)
        for child_document in document.matches:
            self._recurse(child_document)

    def update(self, document: Document, **kwargs) -> None:
        raise NotImplementedError(
            f"{self.__class__.__name__} has not implemented update"
        )


class DropBlob(Executor, TraverseDocumentMixin):
    def update(self, document: Document, **kwargs) -> None:
        document.pop("blob")


class DropEmbedding(Executor, TraverseDocumentMixin):
    def update(self, document: Document, **kwargs) -> None:
        document.pop("embedding")
```

**Comment by JoanFM** [comment]
Hello @matthewfranglen,

You have hit quite an edge case. `BaseExecutor` is our `Base Executor` class to which we default where no `Executor` is added. This `BaseExecutor` is keeping the `docs` unchanged and is uses before the `replicas` when no `uses_before` argument is passed.

I think what u are observing here is the fact that u are applying your own implementation of `BaseExecutor` in an `Executor` that is responsible to load balance the messages to the replicas.

YOu should try changing the name to a non-reserved one.

**Comment by matthewfranglen** [comment]
Ah that's amazing. I did notice that Executor extends BaseExecutor but didn't think that it would result in this conflict.

**Comment by matthewfranglen** [comment]
Thanks once again for the extremely fast help!
