### ISSUE TITLE
blobs getter not working with audio

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#3874]
To reproduce:

```python
import glob
import librosa

from jina import DocumentArray, Document

da = DocumentArray()
# use some sample data from example audio search
audios = glob.glob('/Users/bo/Documents/work/example-audio-search/toy-data/*.mp3')

for audio in audios:
    blob, _ = librosa.load(audio, sr=16000)
    doc = Document(uri=audio, blob=blob)
    da.append(doc)

print(da.blobs.shape)

```

What we get:

```shell
Traceback (most recent call last):
  File "/Users/bo/Documents/work/finetuner/toy_audio.py", line 15, in <module>
    print(da.blobs.shape)
  File "/Users/bo/Documents/work/finetuner/venv/lib/python3.8/site-packages/jina/types/arrays/document.py", line 724, in blobs
    return np.frombuffer(x_mat, dtype=proto.dtype).reshape(
ValueError: cannot reshape array of size 1281531 into shape (8,160512)
```

**Comment by bwanglzu** [comment]
this is not a bug, we expect all audios has the same diemnsionality. Need to adjust in finetuner when input is audio.
