### ISSUE TITLE
500 error when fetching SimpleIndexer

### ISSUE THREAD

**Issue by ugm2** [jina-ai/jina#3988]
Using a .yml file as a description of the flow that is going to be used for indexing, when trying to fetch the SimpleIndexer it gives a 500 error and the message: `ServerSubprocessError: Process(docker) exited on non-zero code: 1`

Using `jina==2.4.9`

index.yml file:
```
jtype: Flow
version: '1'

executors:
  - name: encoder
    uses: 'jinahub://TransformerSentenceEncoder'
    volumes: '~/.cache/huggingface:/root/.cache/huggingface'
  - name: indexer
    uses: 'jinahub://SimpleIndexer'
    uses_with:
      default_traversal_paths: ['c']
  - name: wait
    needs: [indexer]
```

Error:
```
Exception: {"statusCode":500,"message":"ServerSubprocessError: Process(docker) exited on non-zero code: 1"}
```

Traceback:
```
Traceback (most recent call last):
  File "neural_search/api/server.py", line 40, in <module>
    main()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "neural_search/api/server.py", line 30, in main
    index_flow_path=index_flow_path
  File "/home/unai/personal/Neural-Search-JinaAI/neural_search/core/index.py", line 31, in index_docs
    with flow, open(preprocess_path) as fp:
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/flow/base.py", line 1126, in __enter__
    return self.start()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/flow/base.py", line 1173, in start
    self.enter_context(v)
  File "/usr/local/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 208, in __enter__
    return self.start()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 684, in start
    self.enter_context(self.replica_set)
  File "/usr/local/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 468, in __enter__
    self._peas.append(BasePea(_args).start())
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 135, in __init__
    self.runtime_cls = self._get_runtime_cls()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 427, in _get_runtime_cls
    update_runtime_cls(self.args)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/helper.py", line 106, in update_runtime_cls
    _args.uses = HubIO(_hub_args).pull()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/hubio.py", line 686, in pull
    executor = HubIO.fetch_meta(name, tag, secret=secret, force=need_pull)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/helper.py", line 318, in wrapper
    result = func(*args, **kwargs)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/hubio.py", line 591, in fetch_meta
    raise Exception(resp.text)
Exception: {"statusCode":500,"message":"ServerSubprocessError: Process(docker) exited on non-zero code: 1"}
```

**Comment by JoanFM** [comment]
Hey @ugm2,

Thank you for raising this issue. We had experienced ourselves but were convinced that it was fixed in 2.4.9.

Will get back to you as soon as we have definitely fixed the issue.

**Comment by mapleeit** [comment]
Hey, @ugm2 Could you retry now (No need to take any actions on your side)? I think it has been fixed by now.

Feel free to reopen this if there is still the same problem.

**Comment by ugm2** [comment]
Working!! :) Thank you!!! 🥇
