### ISSUE TITLE
LMDBStorage source code version not working

### ISSUE THREAD

**Issue by ugm2** [jina-ai/jina#3990]
Using LMDBStorage from source code (instead that from docker) fails.

I've looked at Jina Hub and it says it should be used this way: `'jinahub://LMDBStorage'`, but it didn't work for me.

Jina AI version: `jina==2.4.9`

yml file:
```
jtype: Flow
version: '1'

executors:
  - name: encoder
    uses: 'jinahub://TransformerSentenceEncoder'
    volumes: '~/.cache/huggingface:/root/.cache/huggingface'
    uses_with:
      device: 'cuda'
      traversal_paths: 'c'
  - name: indexer
    uses: 'jinahub://SimpleIndexer'
  - name: root_indexer
    uses: 'jinahub://LMDBStorage'  
    volumes: 'workspace'
    uses_with:      
      default_traversal_paths: ['r']
    needs: [gateway]
  - name: wait_both
    needs: [indexer, root_indexer]
```

Error:
```
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected stringEnd
```

Traceback:
```
Traceback (most recent call last):
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 3), (line:1, col:4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "neural_search/api/server.py", line 48, in <module>
    main()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "neural_search/api/server.py", line 38, in main
    index_flow_path=index_flow_path
  File "/home/unai/personal/Neural-Search-JinaAI/neural_search/core/index.py", line 31, in index_docs
    with flow, open(preprocess_path) as fp:
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/flow/base.py", line 1126, in __enter__
    return self.start()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/flow/base.py", line 1173, in start
    self.enter_context(v)
  File "/usr/local/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 208, in __enter__
    return self.start()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 684, in start
    self.enter_context(self.replica_set)
  File "/usr/local/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/pods/__init__.py", line 468, in __enter__
    self._peas.append(BasePea(_args).start())
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 135, in __init__
    self.runtime_cls = self._get_runtime_cls()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 427, in _get_runtime_cls
    update_runtime_cls(self.args)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/peapods/peas/helper.py", line 106, in update_runtime_cls
    _args.uses = HubIO(_hub_args).pull()
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/hubio.py", line 737, in pull
    pkg_path=pkg_dist_path,
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/hubapi.py", line 182, in install_package_dependencies
    elif not is_requirements_installed(requirements_file, show_warning=True):
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/helper.py", line 350, in is_requirements_installed
    install_reqs, install_options = _get_install_options(requirements_file)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/jina/hubble/helper.py", line 377, in _get_install_options
    for req_spec in pkg_resources.parse_requirements(req):
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/unai/personal/Neural-Search-JinaAI/.venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected stringEnd
```

**Comment by numb3r3** [comment]
Thanks for your feedback. I'm working on it. Please keep an eye on this PR https://github.com/jina-ai/executors/pull/302

**Comment by numb3r3** [comment]
@ugm2 https://github.com/jina-ai/executors/pull/302 has been merged, please try it again

**Comment by ugm2** [comment]
I am getting the same error after reinstalling jina, do I have to install executors too?

**Comment by numb3r3** [comment]
@ugm2 Could you try pull the executor manually `jina hub pull jinahub://LMDBStorage --force`. After the pulling complete, start the jina flow then.

**Comment by ugm2** [comment]
It worked! I had to execute `jina hub pull jinahub://LMDBStorage --force` and adding `--install-requirements` at the end

**Comment by JoanFM** [comment]
Happy to hear @ugm2 !!! I will close this issue for now, do not hesitate to open a new one in case you have more troubles or doubts!
