### ISSUE TITLE
even the tutorial is not working - cannot reshape array of size 123620208 into shape (3,1052,780)

### ISSUE THREAD

**Issue by askintution** [jina-ai/jina#4108]
Do the process in tutorial, read a bruch of images to search. 

```python
from jina import DocumentArray, Document
import torchvision
model = torchvision.models.resnet50(pretrained=True)  # load ResNet50

def preproc(d: Document):
    print(d.uri)
    return (d.load_uri_to_image_blob()  # load
             .set_image_blob_normalization()  # normalize color 
             .set_image_blob_channel_axis(-1, 0))  # switch color axis
docs = DocumentArray.from_files('xx/*.jpeg').apply(preproc)

docs.embed(model)  # embed via GPU to speedup
```

the error like this

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-18d0c91c8057> in <module>
     10 docs = DocumentArray.from_files('xx/*.jpeg').apply(preproc)
     11 
---> 12 docs.embed(model)  # embed via GPU to speedup

/home/dell/conda/envs/torch10/lib/python3.8/site-packages/docarray/array/mixins/embed.py in embed(self, embed_model, device, batch_size, to_numpy)
     31 
     32         fm = get_framework(embed_model)
---> 33         getattr(self, f'_set_embeddings_{fm}')(
     34             embed_model, device, batch_size, to_numpy
     35         )

/home/dell/conda/envs/torch10/lib/python3.8/site-packages/docarray/array/mixins/embed.py in _set_embeddings_torch(self, embed_model, device, batch_size, to_numpy)
     65         with torch.inference_mode():
     66             for b in self.batch(batch_size):
---> 67                 batch_inputs = torch.tensor(b.blobs, device=device)
     68                 r = embed_model(batch_inputs).cpu().detach()
     69                 b.embeddings = r.numpy() if to_numpy else r

/home/dell/conda/envs/torch10/lib/python3.8/site-packages/docarray/array/mixins/content.py in blobs(self)
     61         """
     62         if self:
---> 63             return NdArray.unravel([d.blob for d in self._pb_body])
     64 
     65     @blobs.setter

/home/dell/conda/envs/torch10/lib/python3.8/site-packages/docarray/ndarray/__init__.py in unravel(protos)
    193         else:
    194             if framework in {'numpy', 'torch', 'paddle', 'tensorflow'}:
--> 195                 x = _unravel_dense_array(
    196                     (d.dense.buffer for d in protos),
    197                     shape=list(first.dense.shape),

/home/dell/conda/envs/torch10/lib/python3.8/site-packages/docarray/ndarray/__init__.py in _unravel_dense_array(source, shape, dtype)
    367     x_mat = b''.join(source)
    368     shape = [-1] + shape
--> 369     return np.frombuffer(x_mat, dtype=dtype).hape(shape)
    370 
    371 

ValueError: cannot reshape array of size 123620208 into shape (3,1052,780)
```

Name: jina
Version: 2.6.3

Name: torch
Version: 1.10.1+cpu

**Comment by azayz** [comment]
Hello, 

Can you try with these versions: 

jina==2.6.3
torch==1.9.1
torchvision==0.10.1

**Comment by askintution** [comment]
@azayz not work. Just me occurred this problem due to my envrionment?

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    docs.embed(model,device='cpu')  # embed via GPU to speedup
  File "/home/dell/conda/envs/torch119/lib/python3.8/site-packages/docarray/array/mixins/embed.py", line 33, in embed
    getattr(self, f'_set_embeddings_{fm}')(
  File "/home/dell/conda/envs/torch119/lib/python3.8/site-packages/docarray/array/mixins/embed.py", line 67, in _set_embeddings_torch
    batch_inputs = torch.tensor(b.blobs, device=device)
  File "/home/dell/conda/envs/torch119/lib/python3.8/site-packages/docarray/array/mixins/content.py", line 63, in blobs
    return NdArray.unravel([d.blob for d in self._pb_body])
  File "/home/dell/conda/envs/torch119/lib/python3.8/site-packages/docarray/ndarray/__init__.py", line 195, in unravel
    x = _unravel_dense_array(
  File "/home/dell/conda/envs/torch119/lib/python3.8/site-packages/docarray/ndarray/__init__.py", line 369, in _unravel_dense_array
    return np.frombuffer(x_mat, dtype=dtype).reshape(shape)
ValueError: cannot reshape array of size 123620208 into shape (3,1052,780)
```


torch                         1.9.1
torchaudio                    0.10.1+cpu
torchvision                   0.10.1
jina                          2.6.3

**Comment by azayz** [comment]
I believe so because for me this is working, I'll keep investigating and let you know

**Comment by vitouphy** [comment]
I have the same problem. 
It seems Jina is storing all the image blobs into one 4D array. Differ image size may be the problem.

![image](https://user-images.githubusercontent.com/35600466/147849214-7c2ec32e-945a-4d4d-af22-ded1a16d7d9f.png)

Try resizing the image.
```python
(d.load_uri_to_image_blob()  # load
     .set_image_blob_shape(shape=(224, 224))
     .set_image_blob_normalization()  # normalize color
     .set_image_blob_channel_axis(-1, 0))  # switch color axis
```

**Comment by askintution** [comment]
@vitouphy thanks,it solved
