### ISSUE TITLE
Question Answering Tutorial gives error in the match function.

### ISSUE THREAD

**Issue by Kumar-Tarun** [jina-ai/jina#4158]
I am following the [QA tutorial](https://docs.jina.ai/tutorials/question-answering-bot/#). While running the code, I ran into the following error (attaching both the code & log): 
**Code:** 
```python
import torch
from sentence_transformers import SentenceTransformer
from transformers import T5Tokenizer, T5ForConditionalGeneration
from jina import DocumentArray, Executor, requests, Document, Flow, DocumentArrayMemmap
from collections import defaultdict

class QuestionGenerator(Executor):
    @requests
    def doc2query(self, docs: DocumentArray, **kwargs):
        """Generates potential questions for each answer"""

        # Load pretrained doc2query models
        self._tokenizer = T5Tokenizer.from_pretrained(
            'castorini/doc2query-t5-base-msmarco'
        )
        self._model = T5ForConditionalGeneration.from_pretrained(
            'castorini/doc2query-t5-base-msmarco'
        )

        for d in docs:
            input_ids = self._tokenizer.encode(d.content, return_tensors='pt')
            # Generte potential queries for each piece of text
            outputs = self._model.generate(
                input_ids=input_ids,
                max_length=64,
                do_sample=True,
                num_return_sequences=10,
            )
            # Decode the outputs ot text and store them
            for output in outputs:
                question = self._tokenizer.decode(
                    output, skip_special_tokens=True
                ).strip()
                d.chunks.append(Document(text=question))

class TextEncoder(Executor):
    def __init__(self, parameters: dict = {'traversal_paths': 'r'}, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model = SentenceTransformer(
            'paraphrase-mpnet-base-v2', device='cpu', cache_folder='.'
        )
        self.parameters = parameters

    @requests(on=['/search', '/index'])
    def encode(self, docs: DocumentArray, **kwargs):
        """Wraps encoder from sentence-transformers package"""
        traversal_paths = self.parameters.get('traversal_paths')
        target = docs.traverse_flat(traversal_paths)

        with torch.no_grad():
            embeddings = self.model.encode(target.texts)
            target.embeddings = embeddings



class SimpleIndexer(Executor):
    """Simple indexer class"""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._docs = DocumentArrayMemmap(".")

    @requests(on='/index')
    def index(self, docs: 'DocumentArray', **kwargs):
        # Stores the index in attribute
        if docs:
            self._docs.extend(docs)

    @requests(on='/search')
    def search(self, docs: 'DocumentArray', **kwargs):
        """Append best matches to each document in docs"""

        # Match query against the index using cosine similarity
        docs.match(
            DocumentArray(self._docs),
            metric='cosine',
            normalization=(1, 0),
            limit=100,
            traversal_rdarray='c,',
        )

        for d in docs:
            match_similarity = defaultdict(float)
            # For each match
            for m in d.matches:
                # Get cosine similarity
                match_similarity[m.parent_id] += m.scores['cosine'].value

            sorted_similarities = sorted(
                match_similarity.items(), key=lambda v: v[1], reverse=True
            )

            # Rank matches by similarity and collect them
            d.matches.clear()
            for k, _ in sorted_similarities:
                m = Document(self._docs[k], copy=True)
                d.matches.append(m)
                # Only return top 10 answers
                if len(d.matches) >= 10:
                    break
            # Remove embedding as it is not needed anymore
            d.pop('embedding')


example_sentences = [
    'Document is the basic data type that Jina operates with',
    'Executor processes a DocumentArray in-place',
    'Jina uses the concept of a flow to tie different executors together'
]

docs = DocumentArray([Document(content=sentence) for sentence in example_sentences])

queries = [
    'What is the basic type in Jina?'
]

user_queries = DocumentArray([Document(content=sentence) for sentence in queries])

indexing_flow = (
    Flow()
    # Generate potential questions using doc2query
    .add(
        name='question_transformer',
        uses=QuestionGenerator,
    )
    # Encode the generated questions
    .add(
        name='text_encoder',
        uses=TextEncoder,
        uses_with={'parameters': {'traversal_paths': 'c'}},
    )
    # Index answers and generated questions
    .add(
        name='simple_indexer',
        uses=SimpleIndexer,
    )
)

with indexing_flow:
    # Run the indexing on all extracted sentences
    indexing_flow.post(on='/index', inputs=docs, on_done=print)

query_flow = (
    Flow()
    # Create vector representations from query
    .add(name='query_transformer', uses=TextEncoder,)
    # Use encoded question to search our index
    .add(
        name='simple_indexer',
        uses=SimpleIndexer,
    )
)

with query_flow:
    # Run question through the query flow and return answer
    search_results = query_flow.post(
        on='/search', inputs=user_queries, return_results=True, on_done=print
    )
```
**Log:**
```
           Flow@17201[I]:🎉 Flow is ready to use!                                                   
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:52071
	🔒 Private network:	10.44.178.17:52071
<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 140398930790288>
           Flow@17201[I]:🎉 Flow is ready to use!                                                   
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:48581
	🔒 Private network:	10.44.178.17:48581
UserWarning: 
            `traversal_ldarray` and `traversal_rdarray` will be removed soon. 
            Instead of doing `da.match(..., traveral_ldarray=[...])`, you can achieve the same via 
            `da.traverse_flat(traversal_paths=[...]).match(...)`.
            Same goes with `da.match(..., traveral_rdarray=[...])`, you can do it via: 
            `da.match(da2.traverse_flat(traversal_paths=[...]))`.             
             (raised from /home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py:101)
 simple_indexer@17312[E]:TypeError("can not determine the array type: ['builtins'].NoneType")
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 226, in _handle
    peapod_name=self.name,
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 171, in handle
    field='groundtruths',
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/executors/__init__.py", line 200, in __call__
    self, **kwargs
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/executors/decorators.py", line 106, in arg_wrapper
    return fn(*args, **kwargs)
  File "jina_neural_search.py", line 79, in search
    traversal_rdarray='c,',
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 145, in match
    dist, idx = lhv._match(rhv, cdist, _limit, normalization, metric_name)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 200, in _match
    dists = cdist(x_mat, y_mat, metric_name)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 131, in <lambda>
    cdist = lambda *x: _cdist(*x, device=device)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/math/distance/__init__.py", line 38, in cdist
    y_type = get_array_type(y_mat)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/ndarray/__init__.py", line 346, in get_array_type
    raise TypeError(f'can not determine the array type: {module_tags}.{class_name}')
TypeError: can not determine the array type: ['builtins'].NoneType
```

**Environment**
Output of `jina --version-full`:
```
- jina 2.6.4
- docarray 0.0.4
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.18.5
- protobuf 3.14.0
- proto-backend cpp
- grpcio 1.34.1
- pyyaml 5.4.1
- python 3.7.9
- platform Linux
- platform-release 3.10.0-1160.45.1.el7.x86_64
- platform-version #1 SMP Fri Sep 24 10:17:16 UTC 2021
- architecture x86_64
- processor x86_64
- uid 345051171014
- session-id 12d93bce-72ef-11ec-a62a-005056a708c6
- uptime 2022-01-11T07:59:27.780067
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
```

**Comment by JoanFM** [comment]
Hello @Kumar-Tarun ,

may u please clean the cache under `~/.jina/`. It seems one of the `executors` is using a different version than the others

**Comment by Kumar-Tarun** [comment]
Hi @JoanFM, `~/.jina/` only had an empty directory `hub-packages`. So, yeah, even after removing that, I'm still facing the same issue.

**Comment by JoanFM** [comment]
It is weird I cannot reproduce. Can you try doing a fresh install of jina?

**Comment by JoanFM** [comment]
Hey @Kumar-Tarun ,

Yes the exact same with torch 1.10.0 in my case.

However, can u try setting `JINA_LOG_LEVEL=DEBUG` as environment variable?

**Comment by Kumar-Tarun** [comment]
@JoanFM After setting this variable, I get the following:
```
⠋ 0/4 waiting question_transformer text_encoder simple_indexer g to be ready...        gateway@31773[D]:setting up sockets...
        gateway@31773[D]:control over ipc:///tmp/tmpgk18am3n
        gateway@31773[D]:input 0.0.0.0:58977
        gateway@31773[D]:input tcp://0.0.0.0:58977 (ROUTER_BIND) output tcp://0.0.0.0:34344 (ROUTER_BIND) control over ipc:///tmp/tmpgk18am3n (PAIR_BIND)
question_transformer@31770[D]:setting up sockets...
question_transformer@31770[D]:control over tcp://0.0.0.0:40005
question_transformer@31770[D]:input 0.0.0.0:32797
question_transformer@31770[D]:input tcp://0.0.0.0:32797 (ROUTER_BIND) output tcp://0.0.0.0:50595 (ROUTER_BIND) control over tcp://0.0.0.0:40005 (PAIR_BIND)
 simple_indexer@31772[D]:setting up sockets...
 simple_indexer@31772[D]:control over tcp://0.0.0.0:57674
 simple_indexer@31772[D]:input 0.0.0.0:49230
 simple_indexer@31772[D]:input tcp://0.0.0.0:49230 (ROUTER_BIND) output tcp://0.0.0.0:58135 (ROUTER_BIND) control over tcp://0.0.0.0:57674 (PAIR_BIND)
⠙ 0/4 waiting question_transformer text_encoder simple_indexer g to be ready...        gateway@31747[D]:ready and listening
 simple_indexer@31772[D]:recv ControlRequest (STATUS)  from ▸simple_indexer/ZEDRuntime▸⚐
 simple_indexer@31772[D]:skip executor: not data request
 simple_indexer@31747[D]:ready and listening
question_transformer@31770[D]:recv ControlRequest (STATUS)  from ▸question_transformer/ZEDRuntime▸⚐
question_transformer@31770[D]:skip executor: not data request
question_transformer@31747[D]:ready and listening
⠦ 3/4 waiting text_encoder to be ready...   text_encoder@31771[D]:setting up sockets...             
   text_encoder@31771[D]:control over tcp://0.0.0.0:44723
   text_encoder@31771[D]:input 0.0.0.0:41828
   text_encoder@31771[D]:input tcp://0.0.0.0:41828 (ROUTER_BIND) output tcp://0.0.0.0:47510 (ROUTER_BIND) control over tcp://0.0.0.0:44723 (PAIR_BIND)
⠧ 3/4 waiting text_encoder to be ready...   text_encoder@31771[D]:recv ControlRequest (STATUS)  from ▸text_encoder/ZEDRuntime▸⚐
   text_encoder@31771[D]:skip executor: not data request
   text_encoder@31747[D]:ready and listening
           Flow@31747[I]:🎉 Flow is ready to use!                                                   
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:46900
	🔒 Private network:	10.44.178.15:46900
           Flow@31747[D]:4 Pods (i.e. 4 Peas) are running in this Flow
     GRPCClient@31747[D]:connected to 0.0.0.0:46900
        gateway@31773[D]:output 0.0.0.0:32797
question_transformer@31770[D]:recv DataRequest (/index) - (45827871140842d29551d1a6ca8c4197)  from gateway▸question_transformer/ZEDRuntime▸⚐
question_transformer@31770[D]:output 0.0.0.0:41828
   text_encoder@31771[D]:recv DataRequest (/index) - (45827871140842d29551d1a6ca8c4197)  from gateway▸question_transformer/ZEDRuntime▸text_encoder/ZEDRuntime▸⚐
   text_encoder@31771[D]:output 0.0.0.0:49230
 simple_indexer@31772[D]:recv DataRequest (/index) - (45827871140842d29551d1a6ca8c4197)  from gateway▸question_transformer/ZEDRuntime▸text_encoder/ZEDRuntime▸simple_indexer/ZEDRuntime▸⚐
 simple_indexer@31772[D]:output 0.0.0.0:58977
<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 139824994868240>
        gateway@31747[D]:waiting for ready or shutdown signal from runtime
        gateway@31747[D]: Cancel runtime
        gateway@31747[D]: Wait to shutdown
        gateway@31773[D]:#sent: 1 #recv: 1 sent_size: 1.1 KB recv_size: 95.4 KB
           JINA@31773[D]:all gateway tasks are cancelled
        gateway@31773[D]:Received message is empty.
        gateway@31773[D]: Process terminated
        gateway@31747[D]: Joining the process
        gateway@31747[D]: Successfully joined the process
        gateway@31747[D]:terminated
        gateway@31747[D]: Joining the process
        gateway@31747[D]: Successfully joined the process
 simple_indexer@31747[D]:waiting for ready or shutdown signal from runtime
 simple_indexer@31747[D]: Cancel runtime
 simple_indexer@31747[D]:Sending TERMINATE command for the 1th time
 simple_indexer@31772[D]:recv ControlRequest (TERMINATE)  from ▸simple_indexer/ZEDRuntime▸⚐
 simple_indexer@31772[D]:Handled #0 during flush of socket
 simple_indexer@31772[D]:Handled #0 during flush of socket
 simple_indexer@31772[D]:Handled #1 during flush of socket
 simple_indexer@31772[D]:Handled #0 during flush of socket
 simple_indexer@31747[D]: Wait to shutdown
 simple_indexer@31772[D]:#sent: 3 #recv: 3 sent_size: 97.9 KB recv_size: 95.6 KB
 simple_indexer@31747[D]: Joining the process
 simple_indexer@31772[D]: Process terminated
 simple_indexer@31747[D]: Successfully joined the process
 simple_indexer@31747[D]:terminated
 simple_indexer@31747[D]: Joining the process
 simple_indexer@31747[D]: Successfully joined the process
   text_encoder@31747[D]:waiting for ready or shutdown signal from runtime
   text_encoder@31747[D]: Cancel runtime
   text_encoder@31747[D]:Sending TERMINATE command for the 1th time
   text_encoder@31771[D]:recv ControlRequest (TERMINATE)  from ▸text_encoder/ZEDRuntime▸⚐
   text_encoder@31771[D]:Handled #0 during flush of socket
   text_encoder@31771[D]:Handled #0 during flush of socket
   text_encoder@31771[D]:Handled #1 during flush of socket
   text_encoder@31771[D]:Handled #0 during flush of socket
   text_encoder@31747[D]: Wait to shutdown
   text_encoder@31771[D]:#sent: 3 #recv: 3 sent_size: 97.8 KB recv_size: 4.7 KB
   text_encoder@31747[D]: Joining the process
   text_encoder@31771[D]: Process terminated
   text_encoder@31747[D]: Successfully joined the process
   text_encoder@31747[D]:terminated
   text_encoder@31747[D]: Joining the process
   text_encoder@31747[D]: Successfully joined the process
question_transformer@31747[D]:waiting for ready or shutdown signal from runtime
question_transformer@31747[D]: Cancel runtime
question_transformer@31747[D]:Sending TERMINATE command for the 1th time
question_transformer@31770[D]:recv ControlRequest (TERMINATE)  from ▸question_transformer/ZEDRuntime▸⚐
question_transformer@31770[D]:Handled #0 during flush of socket
question_transformer@31770[D]:Handled #0 during flush of socket
question_transformer@31770[D]:Handled #1 during flush of socket
question_transformer@31770[D]:Handled #0 during flush of socket
question_transformer@31747[D]: Wait to shutdown
question_transformer@31770[D]:#sent: 3 #recv: 3 sent_size: 7.0 KB recv_size: 1.3 KB
question_transformer@31747[D]: Joining the process
question_transformer@31770[D]: Process terminated
question_transformer@31747[D]: Successfully joined the process
question_transformer@31747[D]:terminated
question_transformer@31747[D]: Joining the process
question_transformer@31747[D]: Successfully joined the process
           Flow@31747[D]:Flow is closed!
⠋ 0/3 waiting query_transformer simple_indexer gateway to be ready...        gateway@31857[D]:setting up sockets...
        gateway@31857[D]:control over ipc:///tmp/tmpz5h_3qni
        gateway@31857[D]:input 0.0.0.0:43993
        gateway@31857[D]:input tcp://0.0.0.0:43993 (ROUTER_BIND) output tcp://0.0.0.0:37799 (ROUTER_BIND) control over ipc:///tmp/tmpz5h_3qni (PAIR_BIND)
        gateway@31747[D]:ready and listening
 simple_indexer@31856[D]:setting up sockets...
 simple_indexer@31856[D]:control over tcp://0.0.0.0:35220
 simple_indexer@31856[D]:input 0.0.0.0:48700
 simple_indexer@31856[D]:input tcp://0.0.0.0:48700 (ROUTER_BIND) output tcp://0.0.0.0:60464 (ROUTER_BIND) control over tcp://0.0.0.0:35220 (PAIR_BIND)
⠙ 1/3 waiting query_transformer simple_indexer to be ready... simple_indexer@31856[D]:recv ControlRequest (STATUS)  from ▸simple_indexer/ZEDRuntime▸⚐
 simple_indexer@31856[D]:skip executor: not data request
 simple_indexer@31747[D]:ready and listening
⠴ 2/3 waiting query_transformer to be ready...query_transformer@31855[D]:setting up sockets...      
query_transformer@31855[D]:control over tcp://0.0.0.0:52639
query_transformer@31855[D]:input 0.0.0.0:41535
query_transformer@31855[D]:input tcp://0.0.0.0:41535 (ROUTER_BIND) output tcp://0.0.0.0:42824 (ROUTER_BIND) control over tcp://0.0.0.0:52639 (PAIR_BIND)
⠦ 2/3 waiting query_transformer to be ready...query_transformer@31855[D]:recv ControlRequest (STATUS)  from ▸query_transformer/ZEDRuntime▸⚐
query_transformer@31855[D]:skip executor: not data request
query_transformer@31747[D]:ready and listening
           Flow@31747[I]:🎉 Flow is ready to use!                                                   
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:53121
	🔒 Private network:	10.44.178.15:53121
           Flow@31747[D]:3 Pods (i.e. 3 Peas) are running in this Flow
     GRPCClient@31747[D]:connected to 0.0.0.0:53121
        gateway@31857[D]:output 0.0.0.0:41535
query_transformer@31855[D]:recv DataRequest (/search) - (24d972447ca741779210897f49f4d478)  from gateway▸query_transformer/ZEDRuntime▸⚐
query_transformer@31855[D]:output 0.0.0.0:48700
 simple_indexer@31856[D]:recv DataRequest (/search) - (24d972447ca741779210897f49f4d478)  from gateway▸query_transformer/ZEDRuntime▸simple_indexer/ZEDRuntime▸⚐
UserWarning: 
            `traversal_ldarray` and `traversal_rdarray` will be removed soon. 
            Instead of doing `da.match(..., traveral_ldarray=[...])`, you can achieve the same via 
            `da.traverse_flat(traversal_paths=[...]).match(...)`.
            Same goes with `da.match(..., traveral_rdarray=[...])`, you can do it via: 
            `da.match(da2.traverse_flat(traversal_paths=[...]))`.             
             (raised from /home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py:101)
 simple_indexer@31856[E]:TypeError("can not determine the array type: ['builtins'].NoneType")
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 226, in _handle
    peapod_name=self.name,
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 171, in handle
    field='groundtruths',
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/executors/__init__.py", line 200, in __call__
    self, **kwargs
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/jina/executors/decorators.py", line 106, in arg_wrapper
    return fn(*args, **kwargs)
  File "jina_neural_search.py", line 78, in search
    traversal_rdarray='c,',
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 145, in match
    dist, idx = lhv._match(rhv, cdist, _limit, normalization, metric_name)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 200, in _match
    dists = cdist(x_mat, y_mat, metric_name)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/array/mixins/match.py", line 131, in <lambda>
    cdist = lambda *x: _cdist(*x, device=device)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/math/distance/__init__.py", line 38, in cdist
    y_type = get_array_type(y_mat)
  File "/home/tkuma64/conda_env/lib/python3.7/site-packages/docarray/ndarray/__init__.py", line 346, in get_array_type
    raise TypeError(f'can not determine the array type: {module_tags}.{class_name}')
TypeError: can not determine the array type: ['builtins'].NoneType
 simple_indexer@31856[D]:output 0.0.0.0:43993
        gateway@31747[D]:waiting for ready or shutdown signal from runtime
        gateway@31747[D]: Cancel runtime
        gateway@31747[D]: Wait to shutdown
        gateway@31857[D]:#sent: 1 #recv: 1 sent_size: 810 Bytes recv_size: 6.4 KB
           JINA@31857[D]:all gateway tasks are cancelled
        gateway@31857[D]:Received message is empty.
        gateway@31857[D]: Process terminated
        gateway@31747[D]: Joining the process
        gateway@31747[D]: Successfully joined the process
        gateway@31747[D]:terminated
        gateway@31747[D]: Joining the process
        gateway@31747[D]: Successfully joined the process
 simple_indexer@31747[D]:waiting for ready or shutdown signal from runtime
 simple_indexer@31747[D]: Cancel runtime
 simple_indexer@31747[D]:Sending TERMINATE command for the 1th time
 simple_indexer@31856[D]:recv ControlRequest (TERMINATE)  from ▸simple_indexer/ZEDRuntime▸⚐
 simple_indexer@31856[D]:Handled #0 during flush of socket
 simple_indexer@31856[D]:Handled #0 during flush of socket
 simple_indexer@31856[D]:Handled #1 during flush of socket
 simple_indexer@31856[D]:Handled #0 during flush of socket
 simple_indexer@31856[D]:#sent: 3 #recv: 3 sent_size: 8.9 KB recv_size: 4.1 KB
 simple_indexer@31747[D]: Wait to shutdown
 simple_indexer@31747[D]: Joining the process
 simple_indexer@31856[D]: Process terminated
 simple_indexer@31747[D]: Successfully joined the process
 simple_indexer@31747[D]:terminated
 simple_indexer@31747[D]: Joining the process
 simple_indexer@31747[D]: Successfully joined the process
query_transformer@31747[D]:waiting for ready or shutdown signal from runtime
query_transformer@31747[D]: Cancel runtime
query_transformer@31747[D]:Sending TERMINATE command for the 1th time
query_transformer@31855[D]:recv ControlRequest (TERMINATE)  from ▸query_transformer/ZEDRuntime▸⚐
query_transformer@31855[D]:Handled #0 during flush of socket
query_transformer@31855[D]:Handled #0 during flush of socket
query_transformer@31855[D]:Handled #1 during flush of socket
query_transformer@31855[D]:Handled #0 during flush of socket
query_transformer@31747[D]: Wait to shutdown
query_transformer@31855[D]:#sent: 3 #recv: 3 sent_size: 6.4 KB recv_size: 1015 Bytes
query_transformer@31747[D]: Joining the process
query_transformer@31855[D]: Process terminated
query_transformer@31747[D]: Successfully joined the process
query_transformer@31747[D]:terminated
query_transformer@31747[D]: Joining the process
query_transformer@31747[D]: Successfully joined the process
           Flow@31747[D]:Flow is closed!
```
Also, what I observed is, in the SimpleIndexer, while indexing the documents, docs.embeddings is `None` and maybe this results in error later on. Whereas the query docs has its `embeddings` attribute filled. Any idea what might be going on?
PS: I also tried with torch-1.10.1, but got the same error.

**Comment by JoanFM** [comment]
When indexing, is not `docs.embeddings` that matters but `docs.traverse_flat('c').embeddings` that you should check

**Comment by Kumar-Tarun** [comment]
@JoanFM, It seems to work when I ran the script from another directory, but not from the same directory where the script was present. Seems like a cache issue. But anyway thanks for your help!
