### ISSUE TITLE
concurrent clients with grpc show lots of warnings

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4172]
**Describe the bug**

```python
pytest -v -s tests/integration/concurrent_clients
```

```
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception in callback functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)
handle: <Handle functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception in callback functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)
handle: <Handle functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception in callback functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)
handle: <Handle functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 147, in grpc._cython.cygrpc.PollerCompletionQueue._handle_events
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception in callback functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)
handle: <Handle functools.partial(<built-in method _handle_events of grpc._cython.cygrpc.PollerCompletionQueue object at 0x7fb4efb05140>, <uvloop.Loop running=True closed=False debug=False>)>
Traceback (most recent call last):
```

**Comment by JoanFM** [comment]
This seems related to having the test using `threading` while it should use `multiprocessing`. GRPC from multiple threads is known to bring issues

**Comment by samsja** [comment]
It is a known upstream issue, grpc does not play well with threading : https://github.com/grpc/grpc/issues/25364

**Comment by eigen2017** [comment]
same issssssssssssssssssue

**Comment by eigen2017** [comment]
> This seems related to having the test using `threading` while it should use `multiprocessing`. GRPC from multiple threads is known to bring issues

pls give a demo for how to change threading to multiprocessing, thks alot~

**Comment by eigen2017** [comment]
> This seems related to having the test using `threading` while it should use `multiprocessing`. GRPC from multiple threads is known to bring issues

different processes cannot solve this, because coexistence is what we need
