### ISSUE TITLE
Flow throwing BadRequestType error when using it with flask

### ISSUE THREAD

**Issue by Akshit17** [jina-ai/jina#4220]
**Describe your problem**

This is my repo [githublink](https://github.com/Akshit17/MovieRecommender/tree/jina-integrate)  where `jina_app.py` and `helper.py` are responsible for flow functioning which work fine on their own when jina_app.py is ran on terminal.
Problem arises when i am using `app.py` Flask using `flask run` to get the matches found by response.  Whenever i make a request for a text query to be searched it is getting processed in the executors in helper.py but the variable `response` in which `flow.post(on='/search', inputs = query, return_results = True)` is stored comes out to be empty with the errors as follow:- jina.excepts.BadRequestType: error when building DataRequestProto from Miami

```
Miami is query and <class 'str'> is its type
        JINA@5587[C]:inputs is not valid! BadRequestType('error when building DataRequestProto from Miami')
Traceback (most recent call last):
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/docarray/document/__init__.py", line 188, in __init__
    obj = json.loads(obj)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 52, in _new_doc_from_data
    d = Document(data, **kwargs)
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/docarray/document/__init__.py", line 234, in __init__
    raise ValueError(f'Fail to construct Document from {obj!r}') from ex
ValueError: Fail to construct Document from 'M'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 17, in _new_data_request_from_batch
    _add_docs_groundtruths(req, batch, data_type, _kwargs)
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 75, in _add_docs_groundtruths
    d, data_type = _new_doc_from_data(content, data_type, **_kwargs)
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 57, in _new_doc_from_data
    return _build_doc_from_content()
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 45, in _build_doc_from_content
    return Document(content=data, **kwargs), DataInputType.CONTENT
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/docarray/document/__init__.py", line 245, in __init__
    self._set_attributes(**kwargs)
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/docarray/document/mixins/attribute.py", line 104, in _set_attributes
    raise AttributeError(f'{k} is not recognized')
AttributeError: host is not recognized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/__init__.py", line 72, in request_generator
    yield _new_data_request_from_batch(
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/jina/clients/request/helper.py", line 19, in _new_data_request_from_batch
    raise BadRequestType(
jina.excepts.BadRequestType: error when building DataRequestProto from Miami
[] IS THE RESPONSE !!!
[2022-01-26 16:41:44,744] ERROR in app: Exception on /positive [POST]
Traceback (most recent call last):
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lethainjection/Desktop/MovieRecommender/myenv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/lethainjection/Desktop/MovieRecommender/app.py", line 62, in main
    recom_list = jina_app.query_results(docs, movie_query)
  File "/home/lethainjection/Desktop/MovieRecommender/jina_app.py", line 93, in query_results
    matches = response[0].data.docs[0].matches
IndexError: list index out of range
```
I have very little knowledge in backend and how `response` is working in jina flow so any workaround regarding this error is appreciated. Thankyou

**Environment**

```
─jina --version-full                                                           
- jina 2.6.3
- docarray 0.0.3
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.20.3
- protobuf 3.19.3
- proto-backend cpp
- grpcio 1.43.0
- pyyaml 6.0
- python 3.9.9
- platform Linux
- platform-release 5.14.0-kali4-amd64
- platform-version #1 SMP Debian 5.14.16-1kali1 (2021-11-05)
- architecture x86_64
- processor
- uid 8796758399109
- session-id af243fba-7e9d-11ec-9141-080027a8d885
- uptime 2022-01-26T17:17:05.420182
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* ```

**Comment by Akshit17** [comment]
When cloning [the repo](https://github.com/Akshit17/MovieRecommender/tree/jina-integrate) to access the data files git LFS will be required as they were originally more than 100MB this process will be very unnecassary  so i am providing a dummy .csv to be used as data file to be in `data_finalize` folder here for you to check the program.
[lite_movies_metadata.csv](https://github.com/jina-ai/jina/files/7941593/lite_movies_metadata.csv)

**Comment by JoanFM** [comment]
What are the steps to run this with `flask` and reproduce the exact issue?

**Comment by JoanFM** [comment]
Hey @Akshit17 ,

I have seen the problem.

The problem is that you pass `query` directly as `inputs`. 

In jina_app you should do in line 84:

```python
 response = flow.post(on='/search', inputs = DocumentAquery([Document(text=query))], return_results = True)
```

**Comment by JoanFM** [comment]
However, I must advice that your usage of Flow is not the correct one. You are indexing and restarting the Flow for every `query`.

You should check this documentation to see the proper usage of Flow as a service and how u can expose your search service via `HTTP` without u needing to handle the `Flask`

https://docs.jina.ai/fundamentals/flow/flow-as-a-service/#flow-with-http-protocol

**Comment by Akshit17** [comment]
Ok I will refer to the documentation page. Also i am not able to figure out why docs.match() is is giving 10 copies of a single match with different ids even with `exclude_self` set to true. Is it a bug or I am doing something wrong there ?

**Comment by JoanFM** [comment]
What do u mean? can u show the behavior? 

Aren't u sure u have been indexing the same document multiple times?

**Comment by Akshit17** [comment]
![match1](https://user-images.githubusercontent.com/69861063/151331752-861e3c02-bd7d-41f1-bb75-c0ab00c9bce5.svg)
This is .plot svg for the query

**Comment by JoanFM** [comment]
What is the actual text of the Document and of the matches?

**Comment by Akshit17** [comment]
For query document the text is 'Miami Avengers' and for all the matches the text is `An assassin helps a young woman avenge the death of her family.`

**Comment by JoanFM** [comment]
> For query document the text is 'Miami Avengers' and for all the matches the text is 'An assassin helps a young woman avenge the death of her family.'

I think the underlying problem is the way u are using Flows, you are indexing all the documents for every query, so My guess is that you have run this multiple times and therefore the document with this answer is indexed multiple times with different ids.

If you correct this usage u should see a good behavior. To validate this, u can delete the workspace and run it from 0

**Comment by Akshit17** [comment]
Ok i will do that. Thankyou for the help

**Comment by JoanFM** [comment]
Hey  @Akshit17 ,

let me know if it worked for u?

**Comment by Akshit17** [comment]
Yes you were right the way I use using flow was the reason I was getting the same matches for the query. However I am still figuring out how do I stop indexing the datafile again and again because if I keep the flow running after it is indexed using flow.block() it works fine when query passed through Swagger UI but at this point my flask app has stopped executing the further lines where I will try to connect to that Flow service i.e code doesn't execute further flow.block(). So I am trying to figure out a workaround for this

**Comment by JoanFM** [comment]
Your flask app should not start the Flow, just assume the Flow is started. This is why I think is better to just use the FastAPI provided by Flow

**Comment by JoanFM** [comment]
Hello @Akshit17,

are you having any progress on this?

**Comment by CatStark** [comment]
Hi @Akshit17,

I'll close the issues since it has been no activity for a while :) but please feel free to open a new ticket if there is something we can still help with.
