### ISSUE TITLE
Got TypeError when tried to use DocumentArray.find

### ISSUE THREAD

**Issue by Wyb0627** [jina-ai/jina#4512]
**Describe the bug**

Hi, I tried to use the DocumentArray.find method to search for tags (Like below in the official document):

Code in official document:
`r = da.find({'tags__h': {'$gt': 10}})`

My code:
`result = total_doc.find({'tags__asin': {'$eq': 11300000.0}})`

However, I got 
```
raise TypeError(f'can not determine the array type: {module_tags}.{class_name}')
TypeError: can not determine the array type: ['builtins'].dict
```

Is it because of my usage of DocumentArray stored in sqlite? If so, is there any other approach suitable for me to find the tag in my DocumentArray?

The detailed information is attached below.

Thank you!

**My Code**

```
import os
import json
from docarray import Document, DocumentArray
import gzip
from tqdm import tqdm

data = []
with gzip.open('meta_Electronics.json.gz') as f:
    for l in f:
        data.append(json.loads(l.strip()))

docarr = DocumentArray.empty(0)
for product in tqdm(data):
    d = Document(tags={
        'asin': product['asin'],
        'title': product['title'] if 'title' in product else '',
        'feature': product['feature'] if 'feature' in product else '',
        'description': product['description'] if 'description' in product else '',
        'price': product['price'] if 'price' in product else '',
        'imageURL': product['imageURL'] if 'imageURL' in product else '',
        'imageURLHighRes': product['imageURLHighRes'] if 'imageURLHighRes' in product else '',
        'also_buy': product['also_buy'] if 'also_buy' in product else '',
        'also_viewed': product['also_viewed'] if 'also_viewed' in product else '',
        'salesRank': product['salesRank'] if 'salesRank' in product else '',
        'brand': product['brand'] if 'brand' in product else '',
        'categories': product['categories'] if 'categories' in product else '',
    }
    )
    docarr.append(d)

total_doc = DocumentArray(
    storage='sqlite',
    config={
        'connection': './generate_data/meta_data.db',
        'table_name': 'meta_data',
    },
)
total_doc.extend(docarr)
print(total_doc[0].to_dict(exclude_none=True))
result = total_doc.find({'tags__asin': {'$eq': 11300000.0}})
print(result[0].to_dict(exclude_none=True))

```
---

**Environment**

```
- protobuf 3.19.1                                                                                         [0/1416]
- proto-backend cpp
- grpcio 1.38.1
- pyyaml 5.4.1
- python 3.7.11
- platform Linux
- platform-release 5.13.0-27-generic
- platform-version #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022
- architecture x86_64
- processor x86_64
- uid 112144060752112
- session-id d8c37ff9-a673-11ec-aa9c-65fe92e7a0f0
- uptime 2022-03-18T13:28:22.927735
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset) 
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset) 
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
```
**Screenshots**

```
python process_data.py 
{'id': '5d8cacb6a66911ecaa9865fe92e7a0f0', 'tags': {'asin': 11300000.0, 'title': 'Genuine Geovision 1 Channel 3rd Party NVR IP Software with USB Dongle Onvif PSIA', 'feature': ['Genuine Geovision 1 Channel NVR IP Software', 'Support 3rd Party IP Camera', 'USB Dongle'], 'description': ['The following camera brands and models have been tested for compatibility with GV-Software.\nGeoVision \tACTi \tArecont Vision \tAXIS \tBosch \tCanon\nCNB \tD-Link \tEtroVision \tHikVision \tHUNT \tIQEye\nJVC \tLG \tMOBOTIX \tPanasonic \tPelco \tSamsung\nSanyo \tSony \tUDP \tVerint \tVIVOTEK \t \n \nCompatible Standard and Protocol\nGV-System also allows for integration with all other IP video devices compatible with ONVIF(V2.0), PSIA (V1.1) standards, or RTSP protocol.\nONVIF \tPSIA \tRTSP \t  \t  \t \nNote: Specifications are subject to change without notice. Every effort has been made to ensure that the information on this Web site is accurate. No liability is assumed for incidental or consequential damages arising from the use of the information or products contained herein.'], 'price': '$65.00', 'imageURL': ['https://images-na.ssl-images-amazon.com/images/I/411uoWa89KL._SS40_.jpg'], 'imageURLHighRes': ['https://images-na.ssl-images-amazon.com/images/I/411uoWa89KL.jpg'], 'also_buy': [], 'also_viewed': '', 'salesRank': '', 'brand': 'GeoVision', 'categories': ''}}
Traceback (most recent call last):
  File "process_data.py", line 42, in <module>
    result = total_doc.find({'tags__asin': {'$eq': 11300000.0}})
  File "/home/yubo/anaconda3/envs/jina/lib/python3.7/site-packages/docarray/array/mixins/find.py", line 82, in find
    _, _ = ndarray.get_array_type(_query)
  File "/home/yubo/anaconda3/envs/jina/lib/python3.7/site-packages/docarray/math/ndarray.py", line 124, in get_array_type
    raise TypeError(f'can not determine the array type: {module_tags}.{class_name}')
TypeError: can not determine the array type: ['builtins'].dict
```

**Comment by hanxiao** [comment]
Thanks a lot for the feedback as this is more docarray related, I'm transferring this issue to the docarray repo
