### ISSUE TITLE
Flow failed to start when port_monitoring is not specified

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4680]
Creating a flow with monitoring enable but without specified a port is not working

```python
def test_flow_without_port():
    with Flow(monitoring=True):
        pass
```

```
test_monitoring.py::test_flow_without_port FAILED                        [100%]  gateway/rep-0@247017[E]:OSError(98, 'Address already in use') during <class 'jina.serve.runtimes.gateway.grpc.GRPCGatewayRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/sami/Documents/workspace/Jina/jina/jina/orchestrate/pods/__init__.py", line 74, in run
    runtime = runtime_cls(
  File "/home/sami/Documents/workspace/Jina/jina/jina/serve/runtimes/asyncio.py", line 66, in __init__
    self._setup_monitoring()
  File "/home/sami/Documents/workspace/Jina/jina/jina/serve/runtimes/monitoring.py", line 20, in _setup_monitoring
    start_http_server(self.args.port_monitoring, registry=self.metrics_registry)
  File "/home/sami/.pyenv/versions/jina3/lib/python3.9/site-packages/prometheus_client/exposition.py", line 144, in start_wsgi_server
    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)
  File "/home/sami/.pyenv/versions/3.9.10/lib/python3.9/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/home/sami/.pyenv/versions/3.9.10/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/sami/.pyenv/versions/3.9.10/lib/python3.9/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/home/sami/.pyenv/versions/3.9.10/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/sami/.pyenv/versions/3.9.10/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
  gateway/rep-0@247017[D]: Process terminated
⠋ 0/1 waiting gateway to be ready...  gateway/rep-0@246958[D]:waiting for ready or shutdown signal from runtime
  gateway/rep-0@246958[D]:shutdown is is already set. Runtime will end gracefully on its own
  gateway/rep-0@246958[D]:terminated
  gateway/rep-0@246958[D]: Joining the process
  gateway/rep-0@246958[D]: Successfully joined the process
⠇ 1/1 waiting  to be ready...           Flow@246958[E]:Flow is aborted due to ['gateway'] can not be started.
           Flow@246958[D]:Flow is closed!
⠇ 1/1 waiting  to be ready...
           Flow@246958[D]:Flow is closed!

tests/integration/monitoring/test_monitoring.py:77 (test_flow_without_port)
def test_flow_without_port():
>       with Flow(monitoring=True):

test_monitoring.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../jina/orchestrate/flow/base.py:1119: in __enter__
    return self.start()
../../../jina/orchestrate/flow/base.py:1174: in start
    self._wait_until_all_ready()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <jina.orchestrate.flow.base.Flow object at 0x7f40027f8a30>

    def _wait_until_all_ready(self):
        results = {}
        threads = []
    
        def _wait_ready(_deployment_name, _deployment):
            try:
                if not _deployment.external:
                    results[_deployment_name] = 'pending'
                    _deployment.wait_start_success()
                    results[_deployment_name] = 'done'
            except Exception as ex:
                results[_deployment_name] = repr(ex)
    
        def _polling_status(status):
    
            while True:
                num_all = len(results)
                num_done = 0
                pendings = []
                for _k, _v in results.items():
                    sys.stdout.flush()
                    if _v == 'pending':
                        pendings.append(_k)
                    else:
                        num_done += 1
                pending_str = colored_rich(' '.join(pendings)[:50], 'yellow')
    
                status.update(
                    f'{num_done}/{num_all} waiting {pending_str} to be ready...'
                )
    
                if not pendings:
                    break
                time.sleep(0.1)
    
        # kick off all deployments wait-ready threads
        for k, v in self:
            t = threading.Thread(
                target=_wait_ready,
                args=(
                    k,
                    v,
                ),
                daemon=True,
            )
            threads.append(t)
            t.start()
    
        console = get_rich_console()
        with console.status('Working...') as status:
            # kick off spinner thread
            t_m = threading.Thread(target=_polling_status, args=[status], daemon=True)
            t_m.start()
    
            # kick off ip getter thread
            addr_table = self._init_table()
    
            t_ip = threading.Thread(
                target=self._get_address_table, args=(addr_table,), daemon=True
            )
            t_ip.start()
    
            for t in threads:
                t.join()
            if t_ip is not None:
                t_ip.join()
            t_m.join()
    
            error_deployments = [k for k, v in results.items() if v != 'done']
            if error_deployments:
                self.logger.error(
                    f'Flow is aborted due to {error_deployments} can not be started.'
                )
                self.close()
>               raise RuntimeFailToStart
E               jina.excepts.RuntimeFailToStart

../../../jina/orchestrate/flow/base.py:1254: RuntimeFailToStart
```

When adding a port it is working
```python
def test_flow_without_port():
    with Flow(monitoring=True, port_monitoring = 8888):
        pass
```

**Comment by samsja** [comment]
turns out it is only a local issue :smiling_face_with_tear:
