### ISSUE TITLE
some problem to serve with TLS

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/jina#4948]
**Describe the bug**

Accoding to the jina docs, I want to serve flow with TLS. The following is my example:

```python
from docarray import DocumentArray
from jina import Flow, Client


with Flow(ssl_certfile='cert/server.crt', ssl_keyfile='cert/server.key') as f:
    c = Client(host='localhost', port=f.port, tls=True)
    c.post(on='/', inputs=DocumentArray.empty(3))
    f.block()
```

**Note**: the `cert` folder is directly copied from `/tests/unit/serve/runtimes/gateway/grpc/cert`

I get the `SSL` error:

```

╭──── 🎉 Flow is ready to serve! ────╮
│  🔗  Protocol          🔐 GRPCS    │
│  🏠     Local     0.0.0.0:59074    │
│  🔒   Private  198.18.0.1:59074    │
╰────────────────────────────────────╯
E0621 16:33:02.467579000 12947820544 ssl_transport_security.cc:1495]   Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0621 16:33:02.477513000 12947820544 ssl_transport_security.cc:1495]   Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "/Users/fengwang/Jina/workspace/oauth2-proxy-example/toy1.py", line 11, in <module>
    c.post(on='/', inputs=DocumentArray.empty(3))
  File "/Users/fengwang/Jina/workspace/jina/jina/clients/mixin.py", line 173, in post
    return run_async(
  File "/Users/fengwang/Jina/workspace/jina/jina/helper.py", line 1323, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/Users/fengwang/.pyenv/versions/3.8.6/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/fengwang/.pyenv/versions/3.8.6/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/fengwang/Jina/workspace/jina/jina/clients/mixin.py", line 164, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/Users/fengwang/Jina/workspace/jina/jina/clients/base/grpc.py", line 155, in _get_results
    raise e
  File "/Users/fengwang/Jina/workspace/jina/jina/clients/base/grpc.py", line 116, in _get_results
    raise ConnectionError(my_details) from None
ConnectionError: failed to connect to all addresses
ERROR  GRPCClient@2529 gRPC error: StatusCode.UNAVAILABLE    [06/21/22 16:33:02]
       failed to connect to all addresses                                       
       The ongoing request is terminated as the server is                       
       not available or closed already.                                         

```

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by numb3r3** [comment]
I will close this issue. Since this is not the problem caused by jina. The certifications used in the example are not registered locally.
