### ISSUE TITLE
Loading Flow from YAML works in one env, not in another

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#5019]
**Describe the bug**
Fashion search is showing a bug when I try to run a Flow I loaded from YAML.

I've tried [replicating the conditions in the simplest manner possible](https://github.com/alexcg1/debug-jina-flow-yaml), but *that* works as expected, despite it being pretty much the exact same code. In essence, it's a single [YAML Flow file](https://github.com/alexcg1/debug-jina-flow-yaml/blob/main/flow.yml) (exact same file in both cases)

In both cases, the code is as simple as:

```python
flow = Flow.from_config("flow.yml")

with flow:
  flow.block()
```

Weirdly it worked fine about a month ago. I re-cloned the repo, created fresh venv and it's failing in a way I haven't seen before.

### Running the code in [fashion search](https://github.com/jina-ai/example-multimodal-fashion-search/tree/debug-constructor)

After running:

```python
with flow:
    flow.block()
```

I get the following errors:

```
helper.py:785)
╭──────── Documents Summary ─────────╮
│                                    │
│   Length                 10        │
│   Homogenous Documents   True      │
│   Common Attributes      ('id',)   │
│   Multimodal dataclass   False     │
│                                    │
╰────────────────────────────────────╯
╭───────────────────── Attributes Summary ─────────────────────╮
│                                                              │
│   Attribute   Data type   #Unique values   Has empty value   │
│  ──────────────────────────────────────────────────────────  │
│   id          ('str',)    10               False             │
│                                                              │
╰──────────────────────────────────────────────────────────────╯
⠋ Waiting ... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/0 -:--:--CRITI… encoder/rep-0@3850107 can not load the executor from /home/alexcg/.jina/hub-package/29r2b26t/config.yml                                         [07/20/22 16:31:43]
⠸ Waiting encoder gateway summary... ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 0:00:00ERROR  encoder/rep-0@3850107 ConstructorError(None, None, "could not determine a constructor for the tag '!CLIPEncoder'", <yaml.error.Mark object at   [07/20/22 16:31:43]
       0x7f3d7b442d00>) during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization                                                                          
        add "--quiet-error" to suppress the exception details                                                                                                             
       ╭───────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────╮                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/orchestrate/pods/__init__.py:74 in run │                    
       │                                                                                                                                             │                    
       │    71 │                                                                                                                                     │                    
       │    72 │   try:                                                                                                                              │                    
       │    73 │   │   _set_envs()                                                                                                                   │                    
       │ ❱  74 │   │   runtime = runtime_cls(                                                                                                        │                    
       │    75 │   │   │   args=args,                                                                                                                │                    
       │    76 │   │   )                                                                                                                             │                    
       │    77 │   except Exception as ex:                                                                                                           │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py:31   │                    
       │ in __init__                                                                                                                                 │                    
       │                                                                                                                                             │                    
       │    28 │   │   :param kwargs: keyword args                                                                                                   │                    
       │    29 │   │   """                                                                                                                           │                    
       │    30 │   │   self._health_servicer = health.HealthServicer(experimental_non_blocking=True)                                                 │                    
       │ ❱  31 │   │   super().__init__(args, **kwargs)                                                                                              │                    
       │    32 │                                                                                                                                     │                    
       │    33 │   async def async_setup(self):                                                                                                      │                    
       │    34 │   │   """                                                                                                                           │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/asyncio.py:66 in        │                    
       │ __init__                                                                                                                                    │                    
       │                                                                                                                                             │                    
       │    63 │   │   │   )                                                                                                                         │                    
       │    64 │   │                                                                                                                                 │                    
       │    65 │   │   self._setup_monitoring()                                                                                                      │                    
       │ ❱  66 │   │   self._loop.run_until_complete(self.async_setup())                                                                             │                    
       │    67 │                                                                                                                                     │                    
       │    68 │   def run_forever(self):                                                                                                            │                    
       │    69 │   │   """                                                                                                                           │                    
       │                                                                                                                                             │                    
       │ /usr/lib/python3.9/asyncio/base_events.py:647 in run_until_complete                                                                         │                    
       │                                                                                                                                             │                    
       │    644 │   │   if not future.done():                                                                                                        │                    
       │    645 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')                                                        │                    
       │    646 │   │                                                                                                                                │                    
       │ ❱  647 │   │   return future.result()                                                                                                       │                    
       │    648 │                                                                                                                                    │                    
       │    649 │   def stop(self):                                                                                                                  │                    
       │    650 │   │   """Stop running the event loop.                                                                                              │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py:58   │                    
       │ in async_setup                                                                                                                              │                    
       │                                                                                                                                             │                    
       │    55 │   │   else:                                                                                                                         │                    
       │    56 │   │   │   self._summary_time = contextlib.nullcontext()                                                                             │                    
       │    57 │   │                                                                                                                                 │                    
       │ ❱  58 │   │   await self._async_setup_grpc_server()                                                                                         │                    
       │    59 │                                                                                                                                     │                    
       │    60 │   async def _async_setup_grpc_server(self):                                                                                         │                    
       │    61 │   │   """                                                                                                                           │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py:68   │                    
       │ in _async_setup_grpc_server                                                                                                                 │                    
       │                                                                                                                                             │                    
       │    65 │   │   # Keep this initialization order                                                                                              │                    
       │    66 │   │   # otherwise readiness check is not valid                                                                                      │                    
       │    67 │   │   # The DataRequestHandler needs to be started BEFORE the grpc server                                                           │                    
       │ ❱  68 │   │   self._data_request_handler = DataRequestHandler(                                                                              │                    
       │    69 │   │   │   self.args, self.logger, self.metrics_registry                                                                             │                    
       │    70 │   │   )                                                                                                                             │                    
       │    71                                                                                                                                       │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/request_handlers/data_… │                    
       │ in __init__                                                                                                                                 │                    
       │                                                                                                                                             │                    
       │    41 │   │   self.args.parallel = self.args.shards                                                                                         │                    
       │    42 │   │   self.logger = logger                                                                                                          │                    
       │    43 │   │   self._is_closed = False                                                                                                       │                    
       │ ❱  44 │   │   self._load_executor(metrics_registry)                                                                                         │                    
       │    45 │   │   self._init_monitoring(metrics_registry)                                                                                       │                    
       │    46 │                                                                                                                                     │                    
       │    47 │   def _init_monitoring(self, metrics_registry: Optional['CollectorRegistry'] = None):                                               │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/serve/runtimes/request_handlers/data_… │                    
       │ in _load_executor                                                                                                                           │                    
       │                                                                                                                                             │                    
       │    79 │   │   :param metrics_registry: Optional prometheus metrics registry that will be                                                    │                    
       │       passed to the executor so that it can expose metrics                                                                                  │                    
       │    80 │   │   """                                                                                                                           │                    
       │    81 │   │   try:                                                                                                                          │                    
       │ ❱  82 │   │   │   self._executor: BaseExecutor = BaseExecutor.load_config(                                                                  │                    
       │    83 │   │   │   │   self.args.uses,                                                                                                       │                    
       │    84 │   │   │   │   uses_with=self.args.uses_with,                                                                                        │                    
       │    85 │   │   │   │   uses_metas=self.args.uses_metas,                                                                                      │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/jaml/__init__.py:760 in load_config    │                    
       │                                                                                                                                             │                    
       │   757 │   │   │   │   # revert yaml's tag and load again, this time with substitution                                                       │                    
       │   758 │   │   │   │   tag_yml = JAML.unescape(JAML.dump(no_tag_yml))                                                                        │                    
       │   759 │   │   │   # load into object, no more substitute                                                                                    │                    
       │ ❱ 760 │   │   │   obj = JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)                                                     │                    
       │   761 │   │   │   if not isinstance(obj, cls):                                                                                              │                    
       │   762 │   │   │   │   raise BadConfigSource(                                                                                                │                    
       │   763 │   │   │   │   │   f'Can not construct {cls} object from {source}. Source might be an                                                │                    
       │       invalid configuration.'                                                                                                               │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/jaml/__init__.py:174 in load           │                    
       │                                                                                                                                             │                    
       │   171 │   │   :return: the Python object                                                                                                    │                    
       │   172 │   │                                                                                                                                 │                    
       │   173 │   │   """                                                                                                                           │                    
       │ ❱ 174 │   │   r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))                                                      │                    
       │   175 │   │                                                                                                                                 │                    
       │   176 │   │   if substitute:                                                                                                                │                    
       │   177 │   │   │   r = JAML.expand_dict(r, context)                                                                                          │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/yaml/__init__.py:81 in load                 │                    
       │                                                                                                                                             │                    
       │    78 │   """                                                                                                                               │                    
       │    79 │   loader = Loader(stream)                                                                                                           │                    
       │    80 │   try:                                                                                                                              │                    
       │ ❱  81 │   │   return loader.get_single_data()                                                                                               │                    
       │    82 │   finally:                                                                                                                          │                    
       │    83 │   │   loader.dispose()                                                                                                              │                    
       │    84                                                                                                                                       │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/yaml/constructor.py:51 in get_single_data   │                    
       │                                                                                                                                             │                    
       │    48 │   │   # Ensure that the stream contains a single document and construct it.                                                         │                    
       │    49 │   │   node = self.get_single_node()                                                                                                 │                    
       │    50 │   │   if node is not None:                                                                                                          │                    
       │ ❱  51 │   │   │   return self.construct_document(node)                                                                                      │                    
       │    52 │   │   return None                                                                                                                   │                    
       │    53 │                                                                                                                                     │                    
       │    54 │   def construct_document(self, node):                                                                                               │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/yaml/constructor.py:55 in                   │                    
       │ construct_document                                                                                                                          │                    
       │                                                                                                                                             │                    
       │    52 │   │   return None                                                                                                                   │                    
       │    53 │                                                                                                                                     │                    
       │    54 │   def construct_document(self, node):                                                                                               │                    
       │ ❱  55 │   │   data = self.construct_object(node)                                                                                            │                    
       │    56 │   │   while self.state_generators:                                                                                                  │                    
       │    57 │   │   │   state_generators = self.state_generators                                                                                  │                    
       │    58 │   │   │   self.state_generators = []                                                                                                │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/yaml/constructor.py:100 in construct_object │                    
       │                                                                                                                                             │                    
       │    97 │   │   │   │   elif isinstance(node, MappingNode):                                                                                   │                    
       │    98 │   │   │   │   │   constructor = self.__class__.construct_mapping                                                                    │                    
       │    99 │   │   if tag_suffix is None:                                                                                                        │                    
       │ ❱ 100 │   │   │   data = constructor(self, node)                                                                                            │                    
       │   101 │   │   else:                                                                                                                         │                    
       │   102 │   │   │   data = constructor(self, tag_suffix, node)                                                                                │                    
       │   103 │   │   if isinstance(data, types.GeneratorType):                                                                                     │                    
       │                                                                                                                                             │                    
       │ /mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/yaml/constructor.py:427 in                  │                    
       │ construct_undefined                                                                                                                         │                    
       │                                                                                                                                             │                    
       │   424 │   │   │   data.__dict__.update(state)                                                                                               │                    
       │   425 │                                                                                                                                     │                    
       │   426 │   def construct_undefined(self, node):                                                                                              │                    
       │ ❱ 427 │   │   raise ConstructorError(None, None,                                                                                            │                    
       │   428 │   │   │   │   "could not determine a constructor for the tag %r" % node.tag,                                                        │                    
       │   429 │   │   │   │   node.start_mark)                                                                                                      │                    
       │   430                                                                                                                                       │                    
       ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                    
       ConstructorError: could not determine a constructor for the tag '!CLIPEncoder'                                                                                     
         in "<unicode string>", line 1, column 1:                                                                                                                         
           !CLIPEncoder                                                                                                                                                   
           ^                                                                                                                                                              
ERROR  Flow@3850089 Flow is aborted due to ['encoder'] can not be started.                                                                             [07/20/22 16:31:45]
Traceback (most recent call last):
  File "/mnt/data/work/repos/examples/example-multimodal-fashion-search/backend/yaml_test.py", line 10, in <module>
    with flow:
  File "/mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1404, in __enter__
    return self.start()
  File "/mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1460, in start
    self._wait_until_all_ready()
  File "/mnt/data/work/repos/examples/example-multimodal-fashion-search/env/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1557, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

### In [simplest working example](https://github.com/alexcg1/debug-jina-flow-yaml)

Everything works smoothly

**Environment**

For each of the cases I used a fresh virtualenv using Python 3.9.13 on Manjaro Linux

For both cases, environment as follows:

```
- jina 3.6.15
- docarray 0.13.32
- jina-proto 0.1.13
- protobuf 3.20.1
- proto-backend cpp
- grpcio 1.47.0
- pyyaml 6.0
- python 3.9.13
- platform Linux
- platform-release 5.10.114-1-MANJARO
- platform-version #1 SMP PREEMPT Mon May 9 07:52:55 UTC 2022
- architecture x86_64
- processor
- uid 242011234364068
- session-id d4230fb4-0839-11ed-815a-dc1ba1a7eaa4
- uptime 2022-07-20T16:39:58.211988
- ci-vendor (unset)
* JINA_AUTH_TOKEN (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEFAULT_WORKSPACE_BASE /home/alexcg/.jina/executor-workspace
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_DISABLE_HEALTHCHECK_LOGS (unset)
* JINA_LOCKS_ROOT (unset)
```

Only difference is `session_id` and `uptime`:

```
15,16c15,16
< - session-id dacd7502-0839-11ed-a764-dc1ba1a7eaa4
< - uptime 2022-07-20T16:40:09.364460
---
> - session-id d4230fb4-0839-11ed-815a-dc1ba1a7eaa4
> - uptime 2022-07-20T16:39:58.211988
```

**Screenshots**

**Comment by alexcg1** [comment]
I even tried copying the code from the minimum working example into the fashion search dir and running it. And it failed with the exact same errors as fashion search. It's all deeply confusing

**Comment by JoanFM** [comment]
Can you please describe the exact steps to reproduce the issue, it is not clear what these `envs` are.

**Comment by JoanFM** [comment]
First of all.

```Flow.from_config``` does not exist, it should be `load_config`.


And for me with this YAML FILE:
```yaml
jtype: Flow
with:
  protocol: http
  #port: 12345
executors:
  - name: encoder
    uses: jinahub://CLIPEncoder
    install_requirements: true
    resources:
      memory: 8G
```

and this code:

```python
from jina import Flow
f = Flow.load_config('flow.yml')
with f:
...     pass

WORKS
```

**Comment by alexcg1** [comment]
> Flow.from_config does not exist, it should be load_config.

That was my bad in the issue, not in my code itself. Forgot the syntax for a moment there. Code uses `Flow.load_config()`

**Comment by alexcg1** [comment]
I'm seeing weird behavior, but I think it's from my end

There's *something* in the fashion search dir that's causing the errors. Even with a fresh venv (with only Jina installed) and using your code in that dir I see the errors. In a fresh dir I don't see errors and it all works fine.

I'll keep digging

**Comment by alexcg1** [comment]
Turns out it was `executor.py` in the backend directory. Renaming it fixes the bug
