### ISSUE TITLE
Setting replicas via environment variables fails

### ISSUE THREAD

**Issue by joschkabraun** [jina-ai/jina#5073]
**Describe the bug**
For the following flow yaml I get an error if I use the environment variable for replicas. But it works fine if I comment that line and use the line above it (which hard codes it to 2),

**Describe how you solve it**
Flow yaml file:
```yaml

jtype: Flow
with:
  name: nowtest
  monitoring: true
  port_expose: 8080
  prefetch: 10
  cors: True
jcloud:
  version: 3.7.0
  retention_days: -1
executors:
  - name: preprocessor
    uses: ${{ ENV.PREPROCESSOR_NAME }}
#    replicas: 2
    replicas: ${{ ENV.PREPROCESSOR_REPLICAS }}
    uses_with:
      app: ${{ ENV.APP }}
    jcloud:
      resources:
        memory: ${{ ENV.PREPROCESSOR_MEMORY }}
        cpu: ${{ ENV.PREPROCESSOR_CPU }}
    env:
      JINA_LOG_LEVEL: DEBUG
```

Error:
```python
Bad response: expecting 201, got 502 from server.
{
 "message": "Internal server error"
}

Traceback (most recent call last):
  File "/Users/joschkabraun/dev/now/benchmark/bechmark_preprocess.py", line 94, in <module>
    client, flow_id = deploy_flow(cpu=cpu, mem=mem, replicas=replicas)
  File "/Users/joschkabraun/dev/now/benchmark/bechmark_preprocess.py", line 38, in deploy_flow
    flow = deploy_wolf(path=flow_yaml, env_file=env_file, name='nowtest')
  File "/Users/joschkabraun/dev/now/now/deployment/deployment.py", line 9, in deploy_wolf
    return CloudFlow(path=path, name=name, env_file=env_file).__enter__()
  File "/Users/joschkabraun/dev/now/venv/lib/python3.9/site-packages/jcloud/flow.py", line 435, in __enter__
    return self._loop.run_until_complete(self.__aenter__())
  File "uvloop/loop.pyx", line 1495, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1488, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 550, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 467, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
  File "/Users/joschkabraun/dev/now/venv/lib/python3.9/site-packages/jcloud/flow.py", line 386, in __aenter__
    await self._deploy()
  File "/Users/joschkabraun/dev/now/venv/lib/python3.9/site-packages/jcloud/flow.py", line 171, in _deploy
    _exit_if_response_error(
  File "/Users/joschkabraun/dev/now/venv/lib/python3.9/site-packages/jcloud/flow.py", line 40, in _exit_if_response_error
    _exit_error(
  File "/Users/joschkabraun/dev/now/venv/lib/python3.9/site-packages/jcloud/flow.py", line 48, in _exit_error
    exit(1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

```

---

**Environment**
```bash
- jina 3.7.0
- docarray 0.13.31
- jina-proto 0.1.13
- protobuf 3.19.4
- proto-backend cpp
- grpcio 1.46.3
- pyyaml 6.0
- python 3.9.12
- platform Darwin
- platform-release 21.6.0
- platform-version Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 190070690681122
- session-id cde20710-1e3a-11ed-8e7d-acde48001122
- uptime 2022-08-17T16:42:22.439872
- ci-vendor (unset)
* JINA_AUTH_TOKEN (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEFAULT_WORKSPACE_BASE /Users/joschkabraun/.jina/executor-workspace
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_DISABLE_HEALTHCHECK_LOGS (unset)
* JINA_LOCKS_ROOT (unset)
```

**Screenshots**

**Comment by JohannesMessner** [comment]
I cannot reproduce this locally.
This works just fine:

`envvarflow.yml`
```yaml
jtype: Flow
version: '1'
with:
  protocol: ${{ ENV.PROTOCOL }}
  prefetch: -1
executors:
- name: exec1
  polling: "ANY"
  uses: jinahub+docker://KindaSlowExecutor/latest
  replicas: ${{ ENV.REPLICAS }}
  port: 55182
  upload_files: []
  port_monitoring: 50590
  env:
    JINA_LOG_LEVEL: DEBUG
```
This runs without issue:
```python
from jina import Flow
from docarray import DocumentArray, Document

import os
os.environ['PROTOCOL'] = 'grpc'
os.environ['REPLICAS'] = '3'

f = Flow.load_config('envvarflow.yml')
f.plot('envvarflow.png')
with f:
    f.post('/', inputs=DocumentArray.empty(3))
```
And produces this Flow:
![envvarflow](https://user-images.githubusercontent.com/44071807/187402992-a39f8ece-f26b-4f52-8e49-67519ba52ceb.png)

Maybe a problem with env var parsing on the JCloud side? @deepankarm
