### ISSUE TITLE
hub push error

### ISSUE THREAD

**Issue by m102981** [jina-ai/jina#5161]
**Describe the bug**
 "Unknown Error" when i push my executor to hub

```
(jina) mxm@moshengdeMacBook-Pro RequestLogger % jina hub push --public .
⠼ Pushing `.` ...🔐 You are logged in to Jina AI as m102981. To log out, use jina auth logout.
⠼ Cloud building ... commitSave: done 631e95ae1290269b87bf5659ERROR  HubIO@32597 Please report this session_id: [yellow bold]6ca978ce-3240-11ed-8f5d-acde48001122[/] to https://github.com/jina-ai/jina/issues                                                                     [09/12/22 10:13:02]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/jina/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/jina/lib/python3.7/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/opt/anaconda3/envs/jina/lib/python3.7/site-packages/jina_cli/api.py", line 186, in hub
    getattr(HubIO(args), args.hub)()
  File "/opt/anaconda3/envs/jina/lib/python3.7/site-packages/jina/hubble/hubio.py", line 569, in push
    raise e
  File "/opt/anaconda3/envs/jina/lib/python3.7/site-packages/jina/hubble/hubio.py", line 528, in push
    f'{overridden_msg or msg or "Unknown Error"} session_id: {session_id}'
Exception: IdentifierNamespaceOccupiedError: 42202 session_id: 6ca978ce-3240-11ed-8f5d-acde48001122

```
**Describe how you solve it**

---

**Environment**

```
(jina) mxm@moshengdeMacBook-Pro RequestLogger % jina --version-full
- jina 3.8.3
- docarray 0.16.3
- jcloud 0.0.35
- jina-hubble-sdk v0.0.0
- jina-proto 0.1.13
- protobuf 3.20.1
- proto-backend cpp
- grpcio 1.47.0
- pyyaml 6.0
- python 3.7.13
- platform Darwin
- platform-release 20.6.0
- platform-version Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022;
  root:xnu-7195.141.29~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 190070690681122
- session-id 1d2e8f18-3241-11ed-abc1-acde48001122
- uptime 2022-09-12T10:17:55.872842
- ci-vendor (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)

```
**Screenshots**

**Comment by delgermurun** [comment]
`IdentifierNamespaceOccupiedError` means executor name already exists (belongs to someone else)
@m102981 please try to rename your executor.

**Comment by m102981** [comment]
thanks you, i rename the  executor, it work now
