### ISSUE TITLE
fix: no retries in case of network problems

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5173]
Hi, can we have retries for indexing documents at the flow?
If I disconnect from the internet during indexing and then connect again after 5 seconds, the flow fails without doing retries.
This issue slows us down when making deployments.

Suggested interface:

```python
f.index(inputs=docs, request_size=10, retries=3, retry_delay=10s)
```
In case a request is not successful even after the retry, the program execution should continue.
Having not complete data is much better for us than completely failing.

```
▶ indexing 67354 documents
⠴ Working... ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:37:44  30% ETA: 1:24:28  
Traceback (most recent call last):
  File "/Users/florianhonicke/jina/now/now/admin/deploy_text_to_video.py", line 39, in <module>
    result = deploy()
  File "/Users/florianhonicke/jina/now/now/admin/deploy_text_to_video.py", line 34, in deploy
    response = cli(args=kwargs)
  File "/Users/florianhonicke/jina/now/now/cli/__init__.py", line 143, in cli
    return run_k8s(os_type=os_type, arch=arch, **args)
  File "/Users/florianhonicke/jina/now/now/run_all_k8s.py", line 168, in run_k8s
    **kwargs,
  File "/Users/florianhonicke/jina/now/now/run_all_k8s.py", line 111, in start_now
    ) = run_backend.run(app_instance, user_input, kubectl_path=kwargs['kubectl_path'])
  File "/Users/florianhonicke/jina/now/now/log/log.py", line 58, in profiled_fun
    result = fun(*args, **kwargs)
  File "/Users/florianhonicke/jina/now/now/run_backend.py", line 62, in run
    return_results=False,
  File "/Users/florianhonicke/jina/now/now/log/log.py", line 58, in profiled_fun
    result = fun(*args, **kwargs)
  File "/Users/florianhonicke/jina/now/now/run_backend.py", line 101, in call_flow
    return_results=return_results,
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/jina/clients/mixin.py", line 271, in post
    **kwargs,
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/jina/helper.py", line 1329, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/jina/clients/mixin.py", line 252, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/Users/florianhonicke/jina/now/env/lib/python3.7/site-packages/jina/clients/base/grpc.py", line 119, in _get_results
    raise ConnectionError(my_details) from None
ConnectionError: Operation timed out
```

**Comment by JoanFM** [comment]
Hey @florian-hoenicke ,

To make sure that the `indexing` continues, please use the `continue_on_error` parameter from the `client.post`.
