### ISSUE TITLE
map_batch()方法中的pool使用Pool出现错误

### ISSUE THREAD

**Issue by xdnjust** [jina-ai/jina#5257]
你好，我在使用jina的map_batch(func, batch_size, pool)功能时候出现bug，
引入模块 from multiprocessing.pool import ThreadPool, Pool
1）首先使用pool=ThreadPool(processes=num_workers)时可以正常运行
2）但是改为pool=Pool(processes=num_workers)时候报错如下：

/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/users_2/d00477216/pytorch_BERT/jina_tokenize/client.py", line 21, in <module>
    test_one(task_name)
  File "/users_2/d00477216/pytorch_BERT/jina_tokenize/client.py", line 14, in test_one
    r = c.post('/', DocumentArray([Document(text=text) for text in data_list]), parameters={'task_name': task_name})
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/mixin.py", line 275, in post
    **kwargs,
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/helper.py", line 1330, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/mixin.py", line 256, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/base/grpc.py", line 100, in _get_results
    logger=self.logger,
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/helper.py", line 81, in callback_exec
    raise BadServer(response.header)
jina.excepts.BadServer: request_id: "b637faa02eef4dd2bfa3f8468d4dbc92"
status {
  code: ERROR
  description: "AttributeError(\"Can\'t pickle local object \'JinaLogger.__init__.<locals>.<lambda>\'\")"
  exception {
    name: "AttributeError"
    args: "Can\'t pickle local object \'JinaLogger.__init__.<locals>.<lambda>\'"
    stacks: "Traceback (most recent call last):\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/runtimes/worker/__init__.py\", line 182, in process_data\n    result = await self._data_request_handler.handle(requests=requests)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py\", line 158, in handle\n    field=\'docs\',\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/__init__.py\", line 301, in __acall__\n    return await self.__acall_endpoint__(__default_endpoint__, **kwargs)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/__init__.py\", line 320, in __acall_endpoint__\n    return await func(self, **kwargs)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/decorators.py\", line 204, in arg_wrapper\n    return await fn(executor_instance, *args, **kwargs)\n"
    stacks: "  File \"server_improve2.py\", line 60, in inference\n    for minibatch, batch_data in docs.map_batch(self._preproc_texts, batch_size=self.per_args.max_batch_size, pool=pool):\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/docarray/array/mixins/parallel.py\", line 215, in map_batch\n    disable=not show_progress,\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/rich/progress.py\", line 169, in track\n    sequence, total=total, description=description, update_period=update_period\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/rich/progress.py\", line 1211, in track\n    for value in sequence:\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/pool.py\", line 748, in next\n    raise value\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/pool.py\", line 431, in _handle_tasks\n    put(task)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/connection.py\", line 206, in send\n    self._send_bytes(_ForkingPickler.dumps(obj))\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/reduction.py\", line 51, in dumps\n    cls(buf, protocol).dump(obj)\n"
    stacks: "AttributeError: Can\'t pickle local object \'JinaLogger.__init__.<locals>.<lambda>\'\n"
    executor: "IRQAInference"
  }
}
exec_endpoint: "/"
target_executor: ""

请问作者如何改进这个问题

**Comment by xdnjust** [comment]
I open a new English-version issue

**Comment by xdnjust** [comment]
I open a new English-version issue
