### ISSUE TITLE
still have a bug when using map_batch() in the latest patch release 3.10.1

### ISSUE THREAD

**Issue by xdnjust** [jina-ai/jina#5260]
I have updated the latest version, but when I using map_batch(func, batch_size, pool=Pool(processes=num_workers)), still have a bug as follows:

Traceback (most recent call last):
  File "/users_2/d00477216/pytorch_BERT/jina_tokenize/client.py", line 21, in <module>
    test_one(task_name)
  File "/users_2/d00477216/pytorch_BERT/jina_tokenize/client.py", line 14, in test_one
    r = c.post('/', DocumentArray([Document(text=text) for text in data_list]), parameters={'task_name': task_name})
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/mixin.py", line 285, in post
    **kwargs,
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/helper.py", line 1334, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/mixin.py", line 262, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/base/grpc.py", line 128, in _get_results
    logger=self.logger,
  File "/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/clients/helper.py", line 81, in callback_exec
    raise BadServer(response.header)
jina.excepts.BadServer: request_id: "56f6ecccf9ff4c608dec6d3396719d6a"
status {
  code: ERROR
  description: "NotImplementedError(\'pool objects cannot be passed between processes or pickled\')"
  exception {
    name: "NotImplementedError"
    args: "pool objects cannot be passed between processes or pickled"
    stacks: "Traceback (most recent call last):\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/runtimes/worker/__init__.py\", line 182, in process_data\n    result = await self._data_request_handler.handle(requests=requests)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py\", line 170, in handle\n    field=\'docs\',\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/__init__.py\", line 293, in __acall__\n    return await self.__acall_endpoint__(__default_endpoint__, **kwargs)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/__init__.py\", line 312, in __acall_endpoint__\n    return await func(self, **kwargs)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/jina/serve/executors/decorators.py\", line 153, in arg_wrapper\n    return await fn(executor_instance, *args, **kwargs)\n"
    stacks: "  File \"server_improve2.py\", line 61, in inference\n    batch_size=self.per_args.max_batch_size, backend=\"process\", num_worker=4):\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/docarray/array/mixins/parallel.py\", line 215, in map_batch\n    disable=not show_progress,\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/rich/progress.py\", line 169, in track\n    sequence, total=total, description=description, update_period=update_period\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/site-packages/rich/progress.py\", line 1211, in track\n    for value in sequence:\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/pool.py\", line 748, in next\n    raise value\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/pool.py\", line 431, in _handle_tasks\n    put(task)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/connection.py\", line 206, in send\n    self._send_bytes(_ForkingPickler.dumps(obj))\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/reduction.py\", line 51, in dumps\n    cls(buf, protocol).dump(obj)\n"
    stacks: "  File \"/home/anaconda3/envs/lc_detectron/lib/python3.7/multiprocessing/pool.py\", line 535, in __reduce__\n    \'pool objects cannot be passed between processes or pickled\'\n"
    stacks: "NotImplementedError: pool objects cannot be passed between processes or pickled\n"
    executor: "IRQAInference"
  }
}
exec_endpoint: "/"
target_executor: ""

**Comment by JoanFM** [comment]
Can you show the exact code that runs in the Executor?

How is this Pool imported?

 I will transfer this ticket to docarray as it seems related to docarray implementation.
