### ISSUE TITLE
hub push err

### ISSUE THREAD

**Issue by big-thousand** [jina-ai/jina#5300]
**Describe the bug**

When I use same account to push executor, sometimes it will triggle IdentifierNamespaceOccupiedError.
But I create executor in same account
```
Run jina hub push ImageOperator
🔐 You are logged in to Jina AI as big-thousand. To log out, use jina auth 
logout.
Please report this session_id: [yellow bold]e732e40b-5383-11ed-8102-b51eb84d5916[/] to https://github.com/jina-ai/jina/issues
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.[14](https://github.com/Sterrenhemel/EmbeddingOp/actions/runs/3311824931/jobs/5467741797#step:5:15)/x64/bin/jina", line 33, in <module>
    sys.exit(load_entry_point('jina==3.10.1', 'console_scripts', 'jina')())
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jina_cli/api.py", line 182, in hub
    getattr(HubIO(args), args.hub_cli)()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/hubble/executor/hubio.py", line 666, in push
    raise e
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/hubble/executor/hubio.py", line 635, in push
    self._async_push(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/hubble/executor/hubio.py", line 404, in _async_push
    raise Exception(f'{ msg or "Unknown Error"} session_id: {session_id}')
Exception: IdentifierNamespaceOccupiedError: Executor name has been taken by others, please provide another one. session_id: e732e40b-5383-11ed-8102-b51eb84d59[16](https://github.com/Sterrenhemel/EmbeddingOp/actions/runs/3311824931/jobs/5467741797#step:5:17)
```
**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
The message says that the `name` of the `Executor` is already taken and that therefore you need to provide an alternative one
