### ISSUE TITLE
grpcio version is incompati in mac os（apple silicon）

### ISSUE THREAD

**Issue by Jecksu** [jina-ai/jina#5356]
Hi, I got an incompatible problem for grpcio=>1.46.0 ,<=1.48.1 when install jina on apple silicon- M1 pro.
I tried to install grpico>=1.46.0,<=1.48.1 manually but failed，error log show below :

```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-q25jp7oq/grpcio_198323f0bc5346ab89e703769d51e053/setup.py", line 541, in <module>
          setuptools.setup(
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
          assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
      AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
```

**Environment**

apple silicon m1 pro ,mac os 13.0
python version： 3.9
pip version ：22.3.1

**Comment by samsja** [comment]
Hey @Jecksu did you check : https://docs.jina.ai/get-started/install/apple-silicon-m1-m2/ ?

**Comment by JoanFM** [comment]
I think this problem is properly documented in the link provided by @samsja,

feel free to reopen if these instructions do not work out for you

**Comment by Jecksu** [comment]
It works ～thank you very much @samsja
