### ISSUE TITLE
Batch indexing documents on a CPU within a docker container fails 

### ISSUE THREAD

**Issue by dpanpat** [jina-ai/jina#5362]
**Describe the bug**
The test case below where a flow is initiated and bulk documents 10000> are indexed spits out the error below after briefly running on CPU machines.  

**To reproduce**

**Build image:**
docker build -t jina-app .
**Run image:**
docker run -t -p 8080:8080 jina-app

**Dockerfile:**
`
FROM jinaai/jina:3.9-standard
ADD . /app
ENV JINA_LOG_LEVEL=DEBUG
WORKDIR /app
ENTRYPOINT ["python", "/app/server.py"]
EXPOSE 8080
`
**server.py:**
`
from docarray import DocumentArray, Document
from jina import Flow, Executor, requests
import re

class ChunkSentencizer(Executor):
    """
    Sentencizes a Document's chunks
    """

    @requests(on="/index")
    def sentencize_text_chunks(self, docs, **kwargs):
        for doc in docs:
            chunks = []
            for chunk in doc.chunks:
                for sentence in re.split(r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s', chunk.text):
                    if sentence.strip() != "":
                        chunks.append(Document({"text": sentence}))
            doc.chunks = chunks

f = (
    Flow(port_expose=8080, prot='http')
    .add(uses=ChunkSentencizer, name="chunk_sentencizer")
    .add(
        name="encoder",
        uses="jinahub://TransformerTorchEncoder",
        replicas=8,
        uses_with={
            "traversal_paths": "@r, c, cc, ccc",
            'pretrained_model_name_or_path': 'sentence-transformers/all-MiniLM-L6-v2'
        },
        install_requirements=True,
    )
)

da = []
for x in range(10000):
    da.append(Document(id=str(x + 1), text="Hello World i am a text", chunks=[Document(text="Hello World i am a large text. " * 1000)]))

with f:
    d = f.index(inputs=DocumentArray(da), show_progress=True, return_responses = True)
`

**ERROR LOG:**
`                                                             [11/07/22 16:24:26]
⠦ Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:04:47   0% ETA: -:--:--  DEBUG  chunk_sentencizer/rep-0@20 recv DataRequest at /index with id: cce2667cb0c7475983117f29dea102e9
                                                              [11/07/22 16:24:41]
⠇ Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:05:00   0% ETA: -:--:--
DEBUG  gateway/rep-0@ 1 waiting for ready or shutdown signal from runtime                                                                                                                                                                             [11/07/22 16:24:53]
DEBUG  gateway/rep-0@ 1 terminate
DEBUG  gateway/rep-0@ 1 terminating the runtime process
DEBUG  gateway/rep-0@ 1 runtime process properly terminated
INFO:     127.0.0.1:53516 - "POST /post HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 405, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 232, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.7/site-packages/jina/serve/runtimes/gateway/http/app.py", line 199, in post
    request_generator(**req_generator_input)
  File "/usr/local/lib/python3.7/site-packages/jina/serve/runtimes/gateway/http/app.py", line 380, in _get_singleton_result
    async for k in streamer.stream(request_iterator=request_iterator):
  File "/usr/local/lib/python3.7/site-packages/jina/serve/stream/__init__.py", line 73, in stream
    async for response in async_iter:
  File "/usr/local/lib/python3.7/site-packages/jina/serve/stream/__init__.py", line 202, in _stream_requests
    response = self._result_handler(future.result())
concurrent.futures._base.CancelledError
INFO:     127.0.0.1:53462 - "POST /post HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

`
---

**Docker images used:**
jinaai/jina:3.9-standard
jinaai/jina:3.10.1-py39-standard

**Comment by JoanFM** [comment]
Are you sure you have enough resources to run this locally with `8` replicas of the model? I bet it takes a lot of memory

**Comment by JoanFM** [comment]
can u check the memory usage of the Docker Image?

**Comment by JoanFM** [comment]
I believe there is some memory error that breaks one Executor and makes it break:

I also think that your `ChunkSentencizer` should change to:

```python
chunks.append(Document(text= sentence))
```

**Comment by dpanpat** [comment]
@JoanFM here is the utilization during runtime. I suspect its the CPU, as memory was not reached the limit.  Ah thanks :) will change the ChunkSentencizer

![image](https://user-images.githubusercontent.com/12422545/200367350-ae197431-00a9-4532-b873-5a7d91278c68.png)

**Comment by dpanpat** [comment]
I was able to get around it by running Jina bare metal on a cuda enabled GPU. 

Let me know if you need any more details.

**Comment by JoanFM** [comment]
How much memory does this model take?

`sentence-transformers/all-MiniLM-L6-v2`?

**Comment by JoanFM** [comment]
Okey I see it is a small model.

**Comment by JoanFM** [comment]
also, maybe u can set `JINA_LOG_LEVEL=DEBUG` environment variable to see DEBUG logs and maybe it shows if one Executor crashed for some reason

**Comment by dpanpat** [comment]
@JoanFM  I have simplified the code a little in the original post, so its easier to debug, I have also updated the DEBUG flag error messages. Now it only has one encoder executor with no replicas. 

Let me know if you need any other details.

**Comment by JoanFM** [comment]
And does it still fail? what do u see? any logs?

**Comment by dpanpat** [comment]
@JoanFM 

I tested it a few times today and am not able to reproduce it anymore. The only change I saw was that the memory used was almost half. I will create another issue if I can track down a more specific test case, 

Closing for now, always appreciate the help 😄 

Darpan
