### ISSUE TITLE
Installing from readme instructions does not work, Flow is aborted due to ['clip_t'] can not be started.

### ISSUE THREAD

**Issue by flamz3d** [jina-ai/jina#5429]
create clean python 3.7 env on debian linux

run 
pip install clip-server
run
python -m clip_server

result
```
           raise FileNotFoundError(f'can not find {path}')                                                                       
       FileNotFoundError: can not find clip_server.executors.clip_torch                                                          
ERROR  Flow@4608 Flow is aborted due to ['clip_t'] can not be started.                                        [11/22/22 13:51:07]
Traceback (most recent call last):
  File "/opt/conda/envs/jina/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/jina/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/clip_server/__main__.py", line 25, in <module>
    with f:
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1556, in __enter__
    return self.start()
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1620, in start
    self._wait_until_all_ready()
  File "/opt/conda/envs/jina/lib/python3.7/site-packages/jina/orchestrate/flow/base.py", line 1719, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by JoanFM** [comment]
Hello @flamz3d ,

thanks for opening the ticket, I am going to move to `clip-as-a-service` repository
