### ISSUE TITLE
Cannot run starter code

### ISSUE THREAD

**Issue by zhimin-z** [jina-ai/jina#5758]
**Describe the bug**
I fail to run the starter code due to a package dependency issue on the intro webpage: https://docs.jina.ai/ 
Weirdly, I did not see there is any dependency requirement for the usage of Jina on this tutorial.

Here is the running error:
```
(jina) jimmy@Jimmys-MacBook-Air D1485AEF-21B6-4AA2-92C4-C352EEF49635 % jina deployment --uses deployment.yml

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


/Users/jimmy/opt/anaconda3/envs/jina/bin/jina deployment    
--uses deployment.yml                                       
╭───────────────────────┬──────────────────────────────────╮
│              Argument │ Value                            │
├───────────────────────┼──────────────────────────────────┤
│                   cli │ deployment                       │
│           compression │ None                             │
│       connection-list │ None                             │
│       deployment-role │ None                             │
│   disable-auto-volume │ False                            │
│         docker-kwargs │ None                             │
│            entrypoint │ None                             │
│                   env │ None                             │
│       env-from-secret │ None                             │
│    exit-on-exceptions │ []                               │
│              external │ False                            │
│    extra-search-paths │ []                               │
│              floating │ False                            │
│          force-update │ False                            │
│                  gpus │ None                             │
│         grpc-metadata │ None                             │
│   grpc-server-options │ None                             │
│                  host │ ['0.0.0.0']                      │
│  install-requirements │ False                            │
│         k8s-namespace │ None                             │
│            log-config │ default                          │
│               metrics │ False                            │
│ metrics-exporter-host │ None                             │
│ metrics-exporter-port │ None                             │
│            monitoring │ False                            │
│                  name │ executor                         │
│                native │ False                            │
│             no-reduce │ False                            │
│      noblock-on-start │ False                            │
│     output-array-type │ None                             │
│              pod-role │ WORKER                           │
│               polling │ ANY                              │
│                  port │ [61342]                          │
│       port-monitoring │ [52527]                          │
│       prefer-platform │ None                             │
│            py-modules │ None                             │
│                 quiet │ False                            │
│           quiet-error │ False                            │
│                reload │ False                            │
│              replicas │ 1                                │
│               retries │ -1                               │
│           runtime-cls │ WorkerRuntime                    │
│              shard-id │ 0                                │
│                shards │ 1                                │
│          timeout-ctrl │ 60                               │
│         timeout-ready │ 600000                           │
│          timeout-send │ None                             │
│                   tls │ False                            │
│  traces-exporter-host │ None                             │
│  traces-exporter-port │ None                             │
│               tracing │ False                            │
│                  uses │ deployment.yml                   │
│            uses-after │ None                             │
│    uses-after-address │ None                             │
│           uses-before │ None                             │
│   uses-before-address │ None                             │
│ uses-dynamic-batching │ None                             │
│            uses-metas │ None                             │
│         uses-requests │ None                             │
│             uses-with │ None                             │
│               volumes │ None                             │
│                  when │ None                             │
│             workspace │ None                             │
│          workspace-id │ 23086b02c50b4146b2c564e9fafd3b88 │
╰───────────────────────┴──────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/importer.py", line 128, in _path_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jimmy/Library/Group Containers/group.com.apple.notes/Accounts/F7487600-B0B2-49EE-AAD0-B633A9B96B40/Media/D1485AEF-21B6-4AA2-92C4-C352EEF49635/translate_executor.py", line 3, in <module>
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
ModuleNotFoundError: No module named 'transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimmy/opt/anaconda3/envs/jina/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina_cli/api.py", line 18, in deployment
    dep = Deployment.load_config(args.uses)
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/jaml/__init__.py", line 742, in load_config
    load_py_modules(
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/jaml/helper.py", line 285, in load_py_modules
    PathImporter.add_modules(*mod)
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/importer.py", line 161, in add_modules
    _path_import(complete_path(m))
  File "/Users/jimmy/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/importer.py", line 130, in _path_import
    raise ImportError(f'can not import module from {absolute_path}') from ex
ImportError: can not import module from /Users/jimmy/Library/Group Containers/group.com.apple.notes/Accounts/F7487600-B0B2-49EE-AAD0-B633A9B96B40/Media/D1485AEF-21B6-4AA2-92C4-C352EEF49635/translate_executor.py
```

**Environment**
OS: MacBook Air M2
Python: 3.10.9
Jina: 3.14.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8592144/224568037-883e9008-62a9-42c1-bbb0-5fa5013097e3.png)

**Comment by alaeddine-13** [comment]
Hey, the dependencies instruction is described here: 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/15269265/224639069-93086407-b655-45d8-b193-b9826066a09e.png">

Although the link is not correctly set, [this PR](https://github.com/jina-ai/jina/pull/5760) should make sure it points to [the installation cell](https://colab.research.google.com/github/jina-ai/jina/blob/master/.github/getting-started/notebook.ipynb#scrollTo=0l-lkmz4H-jW).

Do you find this information enough to install dependencies or you think we should put the actual `pip install` command in the README ?

**Comment by zhimin-z** [comment]
https://github.com/jina-ai/jina/issues/5757

**Comment by zhimin-z** [comment]
> Hey, the dependencies instruction is described here: <img alt="image" width="756" src="https://user-images.githubusercontent.com/15269265/224639069-93086407-b655-45d8-b193-b9826066a09e.png">
> 
> Although the link is not correctly set, [this PR](https://github.com/jina-ai/jina/pull/5760) should make sure it points to [the installation cell](https://colab.research.google.com/github/jina-ai/jina/blob/master/.github/getting-started/notebook.ipynb#scrollTo=0l-lkmz4H-jW).
> 
> Do you find this information enough to install dependencies or you think we should put the actual `pip install` command in the README ?

Check this: https://github.com/jina-ai/jina/pull/5760
