### ISSUE TITLE
dynamic_batching不支持docarray v2

### ISSUE THREAD

**Issue by yuanjie-ai** [jina-ai/jina#5969]
ERROR  executor/rep-0@1323016 AttributeError("type object 'DocList' has no attribute 'empty'")                                                                                           [07/18/23 18:57:45]
        add "--quiet-error" to suppress the exception details                                                                                                                                               
       Traceback (most recent call last):                                                                                                                                                                   
         File "/opt/conda/lib/python3.7/site-packages/jina/serve/runtimes/worker/request_handling.py", line 957, in process_data                                                                            
           requests=requests, tracing_context=tracing_context                                                                                                                                               
         File "/opt/conda/lib/python3.7/site-packages/jina/serve/runtimes/worker/request_handling.py", line 644, in handle                                                                                  
           **self._batchqueue_config[exec_endpoint],                                                                                                                                                        
         File "/opt/conda/lib/python3.7/site-packages/jina/serve/runtimes/worker/batch_queue.py", line 31, in __init__                                                                                      
           self._reset()                                                                                                                                                                                    
         File "/opt/conda/lib/python3.7/site-packages/jina/serve/runtimes/worker/batch_queue.py", line 43, in _reset                                                                                        
           self._big_doc: DocumentArray = DocumentArray.empty()                                                                                                                                             
       AttributeError: type object 'DocList' has no attribute 'empty'

**Comment by yuanjie-ai** [comment]
```
    @requests(on='/')
    @dynamic_batching(preferred_batch_size=10, timeout=200)
    def embed(self, docs: DocList[MyDoc], **kwargs):
```

**Comment by JoanFM** [comment]
Thank you very much for reporting, this is indeed a huge Bug, wil lfix ASAP
