### ISSUE TITLE
How to solve this error? 

### ISSUE THREAD

**Issue by Demogorgon24242** [jina-ai/jina#6158]
**problem**

I am trying to run the readme file program on my local system with Nvidia GPU. However everytime I am executing Deployment.block() with  the parameters it throws the following error. What is the cause of this and how to solve it?
---

**Environment**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\91980\OneDrive\Desktop\Harman_genAI_stack\jina\test.py", line 37, in <module>
    with dep:
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\orchestrator.py", line 14, in __enter__
    return self.start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 1146, in start
    self.enter_context(self.shards[shard_id])
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 236, in __enter__
    pod = PodFactory.build_pod(_args).start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\pods\__init__.py", line 316, in start
    self.worker.start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 269, in run_path
    self._popen = self._Popen(self)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\91980\OneDrive\Desktop\Harman_genAI_stack\jina\test.py", line 37, in <module>
    with dep:
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\orchestrator.py", line 14, in __enter__
    return self.start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 1146, in start
    self.enter_context(self.shards[shard_id])
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\deployments\__init__.py", line 236, in __enter__
    pod = PodFactory.build_pod(_args).start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\site-packages\jina\orchestrate\pods\__init__.py", line 316, in start
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    self.worker.start()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    return Popen(process_obj)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    self._popen = self._Popen(self)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
    _check_not_importing_main()
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "C:\Users\91980\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

![p1](https://github.com/jina-ai/jina/assets/84175705/8b6a4733-d192-491a-b344-3fe8ac1b9d92)

**Comment by JoanFM** [comment]
can u change the code to do:

```python
if __name__ == '__main__':
   dep = Deployment(...)
   with dep:
       dep.block()
```

**Comment by Demogorgon24242** [comment]
Thanks for the recommendation it did work, now I am just facing gateway issues and loading models I shall try and resolve them.

**Comment by JoanFM** [comment]
check the memory available in your system

**Comment by Demogorgon24242** [comment]
Actually it is 16gb so I am fairly sure that is not the issue. However I am now trying to make an executor on Kaggle or Colab and trying to access it via my local system. There is just one doc present for it, but I believe there should be some examples present as well.

**Comment by JoanFM** [comment]
Not sure exactly what is the code u are running, but u need to add the `return_type` parameter to the post to know which return type to expect in output.

**Comment by JoanFM** [comment]
or u need to make sure to use `docarray <= 0.21` in this case.

**Comment by Demogorgon24242** [comment]
yes tuning down the version to docarray=0.21 did work. Thank you, however what was the reason of the error, it would be helpful in future scenarios if you could share some insights.

**Comment by JoanFM** [comment]
u can do a PR to update it, it would be very nice.

The reason is that with the release of docarray 0.30 a very big change in the usage of jina and docarray happened.
