### ISSUE TITLE
Getting no attribute shape error from numpy

### ISSUE THREAD

**Issue by prashant-shahi** [jina-ai/jina#689]
**Problem**
Hello, I used the south-park example and it worked fine but when I tried to change the dataset, I am able to run the indexer but encounter the following error when I use query.

```
  chunk_indexer@9450[I]:indexer size: 0                                                                                                                             │······
  chunk_indexer@9450[W]:you can not query from NumpyIndexer as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are que│······
rying data then the index file must be empty or broken.                                                                                                             │······
  chunk_indexer@9453[I]:indexer size: 0                                                                                                                             │······
  chunk_indexer@9453[W]:you can not query from NumpyIndexer as its "query_handler" is not set. If you are indexing data from scratch then it is fine. If you are que│······
rying data then the index file must be empty or broken.                                                                                                             │······
  chunk_indexer@9450[E]:'NoneType' object has no attribute 'shape'                                                                                                  │······
Traceback (most recent call last):                                                                                                                                  │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 275, in msg_callback                                                 │······
    self.zmqlet.send_message(self._callback(msg))                                                                                                                   │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 264, in _callback                                                    │······
    self.pre_hook(msg).handle(msg).post_hook(msg)                                                                                                                   │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 161, in handle                                                       │······
    self.executor(self.request_type)                                                                                                                                │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/__init__.py", line 565, in __call__                                              │······
    d()                                                                                                                                                             │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/drivers/search.py", line 115, in __call__                                                  │······
    idx, dist = self.exec_fn(embed_vecs, top_k=self.req.top_k)                                                                                                      │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/indexers/vector/numpy.py", line 52, in query                                     │······
    dist = _euclidean(keys, self.query_handler)                                                                                                                     │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/indexers/vector/numpy.py", line 82, in _euclidean                                │······
    A_ext, B_ext = _ext_arrs(A, B)                                                                                                                                  │······
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/indexers/vector/numpy.py", line 74, in _ext_arrs                                 │······
    nB = B.shape[0]                                                                                                                                                 │······
AttributeError: 'NoneType' object has no attribute 'shape' 
```

**Environment**
```
    JINA@9684[E]:theses modules or classes can not be imported ['jina.executors.indexers.vector.milvusdb.milvusdbhandler', 'jina.executors.indexers.vector.mi
lvus']
jina                          0.3.8
jina-proto                    0.0.46
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.0
protobuf                      3.12.2
proto-backend                 cpp
grpcio                        1.30.0
ruamel.yaml                   0.16.10
python                        3.7.5
platform                      Linux
platform-release              5.3.0-1030-gcp
platform-version              #32~18.04.1-Ubuntu SMP Thu Jun 25 19:30:23 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)       
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)
```

**Screenshots**
![screenshot](https://i.imgur.com/Tl84jQY.png)

**Comment by JoanFM** [comment]
Hello @prashant-shahi .

Thank you very much for your interest in **jina**. Could you please provide some more logs? And maybe some examples of the new dataset you tried to index, if that is possible?

**Comment by hackintoshrao** [comment]
Hey @JoanFM ,

I'm @prashant-shahi 's collegue. We are building our product MVP and Jina is a great fit to helps us solve our problem statement. 

Here is the [link](http://play.minio.io/jina/graphql.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20200722%2F%2Fs3%2Faws4_request&X-Amz-Date=20200722T082646Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=f0ee9e5767a40e8b7fc6b8642793e6be420619883e2acfbfb91e3aabc093b152) to the simple dataset which we're trying to index and search.

**Comment by JoanFM** [comment]
Hey @hackintoshrao,

Could you tell how are you extracting the content of the texts? The example loads a file where every line is of the form character[SEP]text. the example splits the sentence and extracts the text as a document. Have you made any changes to the extractor? Are you concatenating these files one after the other?

**Comment by prashant-shahi** [comment]
Hey @JoanFM, yes, you are right. It worked after, we had made changes to the indexer and extractor code.

**Comment by JoanFM** [comment]
Hey @prashant-shahi, @hackintoshrao 

I am glad it worked for you guys!

**Comment by prashant-shahi** [comment]
@JoanFM Thanks!

We have a couple of questions here though.

1) Though we are able to get the *top_k* result text and respective scores, we encounter `kth(=10) out of bounds (1)` exception from *numpy*.

2) Also, the score and result text doesn't seem to be appropriate to the query text.

```
...
        gateway@31132[I]:prefetching 50 requests...                     
        gateway@31132[W]:if this takes too long, you may want to take smaller "--prefetch" or ask client to reduce "--batch-size"
        gateway@31132[I]:prefetching 50 requests takes 0.001 secs                                                                                            
        gateway@31132[I]:send: 0 recv: 0 pending: 0
       splittor@31142[I]:received "search" from gateway__           
       splittor@31151[I]:received "search" from gateway_splittor-head__           
       splittor@31142[I]:received "control" from gateway_splittor-head_splittor-2__
       splittor@31145[I]:received "search" from gateway_splittor-head_splittor-2__
        encoder@31154[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail__                                                     
        encoder@31170[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head__
        encoder@31154[I]:received "control" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head_encoder-2__
        encoder@31157[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head_encoder-2__
  chunk_indexer@31182[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head_encoder-2_encoder-tail__
  chunk_indexer@31192[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head_encoder-2_encoder-tail_chunk_indexer-head__
  chunk_indexer@31189[I]:received "search" from gateway_splittor-head_splittor-2_splittor-tail_encoder-head_encoder-2_encoder-tail_chunk_indexer-head__
  chunk_indexer@31192[E]:kth(=10) out of bounds (1)                                                                                                                                     
Traceback (most recent call last):
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 275, in msg_callback
    self.zmqlet.send_message(self._callback(msg))
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 264, in _callback                                                        
    self.pre_hook(msg).handle(msg).post_hook(msg)                                                                                 
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/peapods/pea.py", line 161, in handle                    
    self.executor(self.request_type)                             
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/__init__.py", line 565, in __call__
    d()                                                  
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/drivers/search.py", line 115, in __call__
    idx, dist = self.exec_fn(embed_vecs, top_k=self.req.top_k)                     
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/jina/executors/indexers/vector/numpy.py", line 56, in query
    idx = np.argpartition(dist, kth=top_k, axis=1)[:, :top_k]                                                                                                      
  File "<__array_function__ internals>", line 6, in argpartition                                             
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 832, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/home/prashantshahi567/new/.env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: kth(=10) out of bounds (1)
```

**Comment by JoanFM** [comment]
Hello @prashant-shahi,

Could you provide more details about the changes you did to the Flow or any code?.

What are the results you are obtaining that you think that makes no sense with the query? and what others do you think should appear in the results? 

I see that you are using some level of `sharding`. Have you checked if you get better results with one single shard or by setting `polling` to `all`?
